return {
    name = "The Rye Beneath The Dye",
    audio = "assets/The Rye Beneath The Dye.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 0.69, direction = "left"},
        {time = 1.37, direction = "right"},
        {time = 2.10, direction = "left"},
        {time = 2.74, direction = "right"},
        {time = 3.56, direction = "down"},
        {time = 4.27, direction = "up"},
        {time = 5.06, direction = "left"},
        {time = 5.71, direction = "right"},
        {time = 6.50, direction = "left"},
        {time = 7.23, direction = "right"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 8.03, direction = "left"},
        {time = 8.72, direction = "right"},
        {time = 9.46, direction = "down"},
        {time = 10.15, direction = "up"},
        {time = 10.81, direction = "left"},
        {time = 11.37, direction = "right"},
        {time = 12.03, direction = "down"},
        {time = 12.35, direction = "left"},
        {time = 12.82, direction = "right"},
        {time = 13.17, direction = "left"},
        {time = 13.49, direction = "right"},
        {time = 13.84, direction = "up"},
        {time = 14.19, direction = "down"},
        {time = 14.56, direction = "left"},
        {time = 14.99, direction = "right"},
        {time = 15.69, direction = "down"},

        -- 16-24 seconds
        -- Intense Pattern
        {time = 16.39, direction = "up"},
        {time = 16.70, direction = "left"},
        {time = 17.08, direction = "right"},
        {time = 17.48, direction = "down"},
        {time = 17.86, direction = "left"},
        {time = 18.58, direction = "left"},
        {time = 19.31, direction = "down"},
        {time = 20.09, direction = "left"},
        {time = 20.85, direction = "left"},
        {time = 21.61, direction = "right"},
        {time = 22.30, direction = "left"},
        {time = 23.01, direction = "up"},
        {time = 23.72, direction = "down"},

        -- 24-32 seconds
        -- Intense Pattern
        {time = 24.48, direction = "right"},
        {time = 25.24, direction = "down"},
        {time = 25.94, direction = "left"},
        {time = 26.72, direction = "left"},
        {time = 27.07, direction = "right"},
        {time = 27.47, direction = "down"},
        {time = 27.95, direction = "up"},
        {time = 28.22, direction = "left"},
        {time = 28.52, direction = "right"},
        {time = 28.93, direction = "down"},
        {time = 29.22, direction = "up"},
        {time = 29.57, direction = "left"},
        {time = 29.89, direction = "right"},
        {time = 30.36, direction = "down"},
        {time = 30.71, direction = "up"},
        {time = 31.06, direction = "up"},
        {time = 31.75, direction = "down"},

        -- 32-40 seconds
        -- Complex Sequence
        {time = 32.51, direction = "up"},
        {time = 33.26, direction = "down"},
        {time = 34.02, direction = "right"},
        {time = 34.75, direction = "down"},
        {time = 35.48, direction = "left"},
        {time = 36.26, direction = "left"},
        {time = 36.99, direction = "up"},
        {time = 37.33, direction = "down"},
        {time = 37.68, direction = "right"},
        {time = 38.46, direction = "right"},
        {time = 39.12, direction = "down"},
        {time = 39.90, direction = "left"},

        -- 40-48 seconds
        -- Complex Sequence
        {time = 40.66, direction = "left"},
        {time = 41.01, direction = "right"},
        {time = 41.41, direction = "left"},
        {time = 42.15, direction = "left"},
        {time = 42.87, direction = "right"},
        {time = 44.36, direction = "up"},
        {time = 45.08, direction = "left"},
        {time = 45.79, direction = "right"},
        {time = 46.50, direction = "down"},
        {time = 47.20, direction = "left"},
        {time = 47.61, direction = "right"},

        -- 48-56 seconds
        -- Complex Sequence
        {time = 48.41, direction = "right"},
        {time = 49.09, direction = "right"},
        {time = 49.87, direction = "right"},
        {time = 50.57, direction = "right"},
        {time = 51.32, direction = "right"},
        {time = 52.06, direction = "left"},
        {time = 52.76, direction = "left"},
        {time = 53.46, direction = "up"},
        {time = 54.18, direction = "up"},
        {time = 54.97, direction = "down"},
        {time = 55.68, direction = "left"},

        -- 56-64 seconds
        -- Complex Sequence
        {time = 56.41, direction = "right"},
        {time = 57.17, direction = "right"},
        {time = 57.87, direction = "right"},
        {time = 58.61, direction = "left"},
        {time = 59.32, direction = "up"},
        {time = 60.06, direction = "right"},
        {time = 60.83, direction = "right"},
        {time = 61.56, direction = "left"},
        {time = 62.27, direction = "up"},
        {time = 63.03, direction = "up"},
        {time = 63.71, direction = "down"},

        -- 64-72 seconds
        -- Complex Sequence
        {time = 64.50, direction = "down"},
        {time = 65.22, direction = "up"},
        {time = 65.92, direction = "up"},
        {time = 66.68, direction = "left"},
        {time = 67.41, direction = "right"},
        {time = 68.14, direction = "right"},
        {time = 68.88, direction = "up"},
        {time = 69.58, direction = "down"},
        {time = 70.26, direction = "left"},
        {time = 70.71, direction = "right"},
        {time = 71.12, direction = "left"},
        {time = 71.79, direction = "right"},

        -- 72-80 seconds
        -- Complex Sequence
        {time = 72.53, direction = "left"},
        {time = 73.29, direction = "down"},
        {time = 73.99, direction = "right"},
        {time = 74.70, direction = "up"},
        {time = 75.47, direction = "left"},
        {time = 76.24, direction = "left"},
        {time = 76.94, direction = "right"},
        {time = 77.70, direction = "right"},
        {time = 78.43, direction = "up"},
        {time = 79.14, direction = "down"},
        {time = 79.83, direction = "up"},

        -- 80-88 seconds
        -- Complex Sequence
        {time = 80.65, direction = "left"},
        {time = 81.27, direction = "right"},
        {time = 82.10, direction = "down"},
        {time = 82.86, direction = "up"},
        {time = 83.65, direction = "down"},
        {time = 84.13, direction = "left"},
        {time = 84.94, direction = "right"},
        {time = 85.77, direction = "right"},
        {time = 86.39, direction = "up"},
        {time = 86.94, direction = "down"},
        {time = 87.61, direction = "up"},

        -- 88-96 seconds
        -- Complex Sequence
        {time = 88.34, direction = "left"},
        {time = 88.97, direction = "right"},
        {time = 89.66, direction = "down"},
        {time = 90.41, direction = "up"},
        {time = 91.29, direction = "left"},
        {time = 91.99, direction = "right"},
        {time = 92.73, direction = "down"},
        {time = 93.36, direction = "up"},
        {time = 94.11, direction = "down"},
        {time = 94.78, direction = "left"},
        {time = 95.62, direction = "right"},

        -- 96-104 seconds
        -- Complex Sequence
        {time = 96.42, direction = "left"},
        {time = 97.16, direction = "right"},
        {time = 97.83, direction = "up"},
        {time = 98.65, direction = "up"},
        {time = 99.36, direction = "left"},
        {time = 100.09, direction = "down"},
        {time = 100.83, direction = "left"},
        {time = 101.59, direction = "down"},
        {time = 102.27, direction = "right"},
        {time = 103.03, direction = "down"},
        {time = 103.75, direction = "right"},

        -- 104-112 seconds
        -- Intense Pattern
        {time = 104.48, direction = "left"},
        {time = 104.83, direction = "right"},
        {time = 105.21, direction = "down"},
        {time = 105.61, direction = "up"},
        {time = 105.96, direction = "left"},
        {time = 106.70, direction = "left"},
        {time = 107.45, direction = "up"},
        {time = 108.14, direction = "up"},
        {time = 108.85, direction = "down"},
        {time = 109.61, direction = "down"},
        {time = 110.34, direction = "down"},
        {time = 111.10, direction = "down"},
        {time = 111.80, direction = "left"},

        -- 112-120 seconds
        -- Intense Pattern
        {time = 112.55, direction = "right"},
        {time = 113.23, direction = "down"},
        {time = 114.02, direction = "up"},
        {time = 114.79, direction = "up"},
        {time = 115.49, direction = "left"},
        {time = 116.16, direction = "right"},
        {time = 116.89, direction = "down"},
        {time = 117.30, direction = "left"},
        {time = 117.67, direction = "right"},
        {time = 118.05, direction = "right"},
        {time = 118.45, direction = "right"},
        {time = 118.81, direction = "right"},
        {time = 119.18, direction = "right"},
        {time = 119.54, direction = "right"},
        {time = 119.89, direction = "right"},

        -- 120-128 seconds
        -- Intense Pattern
        {time = 120.26, direction = "right"},
        {time = 120.63, direction = "left"},
        {time = 121.02, direction = "left"},
        {time = 121.42, direction = "left"},
        {time = 121.76, direction = "left"},
        {time = 122.09, direction = "up"},
        {time = 122.46, direction = "up"},
        {time = 122.81, direction = "up"},
        {time = 123.18, direction = "up"},
        {time = 123.53, direction = "down"},
        {time = 123.91, direction = "down"},
        {time = 124.30, direction = "down"},
        {time = 124.70, direction = "down"},
        {time = 125.07, direction = "down"},
        {time = 125.44, direction = "down"},
        {time = 125.79, direction = "down"},
        {time = 126.13, direction = "down"},
        {time = 126.55, direction = "left"},
        {time = 126.93, direction = "left"},
        {time = 127.30, direction = "left"},
        {time = 127.63, direction = "left"},

        -- 128-136 seconds
        -- Intense Pattern
        {time = 128.00, direction = "right"},
        {time = 128.37, direction = "right"},
        {time = 128.69, direction = "down"},
        {time = 129.06, direction = "left"},
        {time = 129.45, direction = "up"},
        {time = 129.84, direction = "left"},
        {time = 130.18, direction = "up"},
        {time = 130.50, direction = "left"},
        {time = 130.84, direction = "up"},
        {time = 131.27, direction = "left"},
        {time = 131.63, direction = "right"},
        {time = 132.05, direction = "down"},
        {time = 132.43, direction = "right"},
        {time = 132.77, direction = "down"},
        {time = 133.12, direction = "right"},
        {time = 133.50, direction = "down"},
        {time = 133.88, direction = "left"},
        {time = 134.56, direction = "down"},
        {time = 135.34, direction = "left"},

        -- 136-144 seconds
        -- Basic Pattern
        {time = 136.06, direction = "left"},
        {time = 136.81, direction = "down"},
        {time = 137.51, direction = "left"},
        {time = 138.27, direction = "down"},
        {time = 139.00, direction = "right"},
        {time = 139.66, direction = "down"},
        {time = 140.49, direction = "right"},
        {time = 141.22, direction = "left"}
    }
}