return {
    name = "Panic! At the Arcade",
    audio = "assets/Panic! At the Arcade.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 0.74, direction = "left"},
        {time = 1.51, direction = "right"},
        {time = 1.93, direction = "left"},
        {time = 2.26, direction = "left"},
        {time = 2.59, direction = "right"},
        {time = 2.91, direction = "right"},
        {time = 3.22, direction = "up"},
        {time = 3.55, direction = "up"},
        {time = 3.85, direction = "down"},
        {time = 4.20, direction = "down"},
        {time = 4.51, direction = "up"},
        {time = 4.84, direction = "up"},
        {time = 5.15, direction = "up"},
        {time = 5.46, direction = "down"},
        {time = 5.81, direction = "down"},
        {time = 6.14, direction = "left"},
        {time = 6.48, direction = "left"},
        {time = 6.81, direction = "right"},
        {time = 7.15, direction = "right"},
        {time = 7.47, direction = "down"},
        {time = 7.78, direction = "down"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 9.14, direction = "left"},
        {time = 9.39, direction = "left"},
        {time = 9.72, direction = "right"},
        {time = 10.05, direction = "right"},
        {time = 10.30, direction = "left"},
        {time = 10.64, direction = "right"},
        {time = 11.00, direction = "up"},
        {time = 11.33, direction = "down"},
        {time = 11.64, direction = "up"},
        {time = 11.96, direction = "left"},
        {time = 12.30, direction = "left"},
        {time = 12.61, direction = "right"},
        {time = 12.94, direction = "right"},
        {time = 13.24, direction = "left"},
        {time = 13.59, direction = "left"},
        {time = 14.24, direction = "right"},
        {time = 14.57, direction = "down"},
        {time = 14.89, direction = "down"},
        {time = 15.23, direction = "up"},
        {time = 15.53, direction = "up"},
        {time = 15.87, direction = "left"},

        -- 16-24 seconds
        -- Intense Pattern
        {time = 16.21, direction = "left"},
        {time = 16.54, direction = "right"},
        {time = 16.86, direction = "right"},
        {time = 17.18, direction = "left"},
        {time = 17.50, direction = "left"},
        {time = 17.83, direction = "right"},
        {time = 18.14, direction = "right"},
        {time = 18.45, direction = "left"},
        {time = 18.79, direction = "left"},
        {time = 19.09, direction = "right"},
        {time = 19.44, direction = "right"},
        {time = 19.79, direction = "up"},
        {time = 20.11, direction = "up"},
        {time = 20.43, direction = "down"},
        {time = 20.75, direction = "down"},
        {time = 21.07, direction = "left"},
        {time = 21.36, direction = "left"},
        {time = 21.69, direction = "right"},
        {time = 22.02, direction = "right"},
        {time = 22.35, direction = "left"},
        {time = 22.67, direction = "left"},
        {time = 23.00, direction = "right"},
        {time = 23.32, direction = "right"},
        {time = 23.64, direction = "up"},
        {time = 23.98, direction = "up"},

        -- 24-32 seconds
        -- Intense Pattern
        {time = 24.30, direction = "down"},
        {time = 24.61, direction = "down"},
        {time = 24.94, direction = "left"},
        {time = 25.27, direction = "left"},
        {time = 25.59, direction = "right"},
        {time = 25.93, direction = "right"},
        {time = 26.28, direction = "left"},
        {time = 26.59, direction = "left"},
        {time = 26.88, direction = "right"},
        {time = 27.19, direction = "right"},
        {time = 27.52, direction = "up"},
        {time = 27.85, direction = "up"},
        {time = 28.18, direction = "down"},
        {time = 28.47, direction = "down"},
        {time = 28.82, direction = "left"},
        {time = 29.14, direction = "left"},
        {time = 29.46, direction = "right"},
        {time = 29.79, direction = "right"},
        {time = 30.14, direction = "up"},
        {time = 30.48, direction = "up"},
        {time = 30.84, direction = "left"},
        {time = 31.13, direction = "right"},
        {time = 31.48, direction = "left"},
        {time = 31.79, direction = "right"},

        -- 32-40 seconds
        -- Intense Pattern
        {time = 32.12, direction = "left"},
        {time = 32.43, direction = "right"},
        {time = 32.76, direction = "left"},
        {time = 33.09, direction = "left"},
        {time = 33.41, direction = "left"},
        {time = 33.71, direction = "right"},
        {time = 34.01, direction = "right"},
        {time = 34.32, direction = "right"},
        {time = 34.63, direction = "right"},
        {time = 34.96, direction = "left"},
        {time = 35.29, direction = "left"},
        {time = 35.68, direction = "left"},
        {time = 36.00, direction = "left"},
        {time = 36.30, direction = "left"},
        {time = 36.62, direction = "right"},
        {time = 36.93, direction = "right"},
        {time = 37.24, direction = "right"},
        {time = 37.59, direction = "right"},
        {time = 37.94, direction = "left"},
        {time = 38.57, direction = "right"},
        {time = 38.91, direction = "left"},
        {time = 39.25, direction = "right"},
        {time = 39.55, direction = "left"},
        {time = 39.86, direction = "right"},

        -- 40-48 seconds
        -- Intense Pattern
        {time = 40.19, direction = "left"},
        {time = 40.53, direction = "right"},
        {time = 40.84, direction = "left"},
        {time = 41.17, direction = "right"},
        {time = 41.50, direction = "left"},
        {time = 41.85, direction = "down"},
        {time = 42.18, direction = "up"},
        {time = 42.49, direction = "down"},
        {time = 42.81, direction = "left"},
        {time = 43.12, direction = "right"},
        {time = 43.43, direction = "left"},
        {time = 43.76, direction = "right"},
        {time = 44.09, direction = "left"},
        {time = 44.41, direction = "right"},
        {time = 44.74, direction = "right"},
        {time = 45.07, direction = "right"},
        {time = 45.37, direction = "right"},
        {time = 45.70, direction = "left"},
        {time = 46.04, direction = "left"},
        {time = 46.36, direction = "right"},
        {time = 46.67, direction = "right"},
        {time = 47.34, direction = "down"},
        {time = 47.65, direction = "down"},
        {time = 47.97, direction = "down"},

        -- 48-56 seconds
        -- Intense Pattern
        {time = 48.30, direction = "up"},
        {time = 48.62, direction = "down"},
        {time = 48.95, direction = "up"},
        {time = 49.28, direction = "up"},
        {time = 49.60, direction = "left"},
        {time = 49.92, direction = "left"},
        {time = 50.21, direction = "left"},
        {time = 50.54, direction = "right"},
        {time = 50.89, direction = "right"},
        {time = 51.20, direction = "right"},
        {time = 51.85, direction = "left"},
        {time = 52.17, direction = "left"},
        {time = 52.51, direction = "right"},
        {time = 52.86, direction = "right"},
        {time = 53.15, direction = "right"},
        {time = 53.52, direction = "up"},
        {time = 53.84, direction = "up"},
        {time = 54.15, direction = "down"},
        {time = 54.47, direction = "down"},
        {time = 54.81, direction = "left"},
        {time = 55.13, direction = "left"},
        {time = 55.44, direction = "right"},
        {time = 55.77, direction = "right"},

        -- 56-64 seconds
        -- Intense Pattern
        {time = 56.10, direction = "up"},
        {time = 56.42, direction = "down"},
        {time = 56.76, direction = "up"},
        {time = 57.05, direction = "down"},
        {time = 57.39, direction = "left"},
        {time = 57.70, direction = "left"},
        {time = 57.99, direction = "right"},
        {time = 58.37, direction = "left"},
        {time = 58.70, direction = "right"},
        {time = 59.02, direction = "left"},
        {time = 59.33, direction = "right"},
        {time = 59.65, direction = "left"},
        {time = 59.96, direction = "right"},
        {time = 60.30, direction = "right"},
        {time = 60.64, direction = "right"},
        {time = 60.94, direction = "right"},
        {time = 61.28, direction = "left"},
        {time = 61.59, direction = "left"},
        {time = 61.93, direction = "down"},
        {time = 62.25, direction = "down"},
        {time = 62.57, direction = "up"},
        {time = 62.90, direction = "up"},
        {time = 63.21, direction = "down"},
        {time = 63.55, direction = "left"},
        {time = 63.87, direction = "right"},

        -- 64-72 seconds
        -- Intense Pattern
        {time = 64.21, direction = "left"},
        {time = 64.54, direction = "right"},
        {time = 64.85, direction = "left"},
        {time = 65.18, direction = "right"},
        {time = 65.49, direction = "right"},
        {time = 65.79, direction = "right"},
        {time = 66.13, direction = "right"},
        {time = 66.46, direction = "left"},
        {time = 66.78, direction = "right"},
        {time = 67.14, direction = "left"},
        {time = 67.44, direction = "right"},
        {time = 67.81, direction = "up"},
        {time = 68.09, direction = "up"},
        {time = 68.38, direction = "down"},
        {time = 68.75, direction = "up"},
        {time = 69.06, direction = "down"},
        {time = 69.41, direction = "left"},
        {time = 69.71, direction = "right"},
        {time = 70.03, direction = "left"},
        {time = 70.35, direction = "right"},
        {time = 70.69, direction = "right"},
        {time = 71.00, direction = "right"},
        {time = 71.30, direction = "right"},
        {time = 71.64, direction = "left"},
        {time = 71.95, direction = "left"},

        -- 72-80 seconds
        -- Intense Pattern
        {time = 72.28, direction = "right"},
        {time = 72.61, direction = "right"},
        {time = 72.96, direction = "left"},
        {time = 73.26, direction = "left"},
        {time = 73.58, direction = "right"},
        {time = 73.91, direction = "right"},
        {time = 74.25, direction = "left"},
        {time = 74.57, direction = "left"},
        {time = 74.88, direction = "right"},
        {time = 75.19, direction = "right"},
        {time = 75.54, direction = "left"},
        {time = 75.85, direction = "left"},
        {time = 76.19, direction = "left"},
        {time = 76.49, direction = "left"},
        {time = 76.83, direction = "right"},
        {time = 77.17, direction = "right"},
        {time = 77.49, direction = "right"},
        {time = 77.78, direction = "right"},
        {time = 78.11, direction = "left"},
        {time = 78.45, direction = "left"},
        {time = 78.76, direction = "right"},
        {time = 79.07, direction = "right"},
        {time = 79.43, direction = "up"},
        {time = 79.73, direction = "up"},

        -- 80-88 seconds
        -- Intense Pattern
        {time = 80.06, direction = "down"},
        {time = 80.37, direction = "down"},
        {time = 80.74, direction = "left"},
        {time = 81.06, direction = "left"},
        {time = 81.38, direction = "right"},
        {time = 81.65, direction = "right"},
        {time = 81.99, direction = "up"},
        {time = 82.32, direction = "up"},
        {time = 82.93, direction = "down"},
        {time = 83.28, direction = "down"},
        {time = 83.60, direction = "down"},
        {time = 83.90, direction = "left"},
        {time = 84.23, direction = "left"},
        {time = 84.60, direction = "right"},
        {time = 84.92, direction = "right"},
        {time = 85.23, direction = "right"},
        {time = 85.55, direction = "right"},
        {time = 85.93, direction = "left"},
        {time = 86.25, direction = "left"},
        {time = 86.58, direction = "left"},
        {time = 86.90, direction = "left"},
        {time = 87.25, direction = "left"},
        {time = 87.57, direction = "left"},
        {time = 87.88, direction = "down"},

        -- 88-96 seconds
        -- Intense Pattern
        {time = 88.58, direction = "up"},
        {time = 88.89, direction = "down"},
        {time = 89.23, direction = "up"},
        {time = 89.52, direction = "down"},
        {time = 89.82, direction = "up"},
        {time = 90.13, direction = "down"},
        {time = 90.47, direction = "left"},
        {time = 90.78, direction = "right"},
        {time = 91.13, direction = "left"},
        {time = 91.43, direction = "right"},
        {time = 91.78, direction = "left"},
        {time = 92.10, direction = "right"},
        {time = 92.43, direction = "left"},
        {time = 93.13, direction = "left"},
        {time = 93.69, direction = "right"},
        {time = 94.36, direction = "left"},
        {time = 94.97, direction = "right"},
        {time = 95.69, direction = "left"},

        -- 96-104 seconds
        -- Complex Sequence
        {time = 96.31, direction = "right"},
        {time = 96.98, direction = "left"},
        {time = 97.61, direction = "right"},
        {time = 98.26, direction = "left"},
        {time = 98.89, direction = "up"},
        {time = 99.55, direction = "down"},
        {time = 100.20, direction = "left"},
        {time = 100.85, direction = "right"},
        {time = 101.50, direction = "down"},
        {time = 102.17, direction = "right"},
        {time = 102.79, direction = "down"},
        {time = 103.59, direction = "left"},

        -- 104-112 seconds
        -- Basic Pattern
        {time = 104.46, direction = "right"},
        {time = 105.05, direction = "right"},
        {time = 105.70, direction = "right"},
        {time = 106.35, direction = "right"},
        {time = 106.97, direction = "right"},
        {time = 107.60, direction = "right"},
        {time = 109.31, direction = "left"},
        {time = 109.97, direction = "right"}
    }
}