return {
    name = "ハンバーグパラダイス!",
    audio = "assets/ハンバーグパラダイス!.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 0.86, direction = "left"},
        {time = 1.59, direction = "right"},
        {time = 2.23, direction = "left"},
        {time = 2.85, direction = "right"},
        {time = 3.44, direction = "down"},
        {time = 4.10, direction = "left"},
        {time = 4.74, direction = "right"},
        {time = 5.46, direction = "left"},
        {time = 5.76, direction = "left"},
        {time = 6.07, direction = "right"},
        {time = 6.39, direction = "right"},
        {time = 6.76, direction = "left"},
        {time = 7.07, direction = "left"},
        {time = 7.34, direction = "right"},
        {time = 7.63, direction = "right"},
        {time = 7.96, direction = "left"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 8.28, direction = "left"},
        {time = 8.62, direction = "right"},
        {time = 8.87, direction = "right"},
        {time = 9.22, direction = "up"},
        {time = 9.55, direction = "down"},
        {time = 9.86, direction = "left"},
        {time = 10.16, direction = "right"},
        {time = 10.50, direction = "left"},
        {time = 10.82, direction = "right"},
        {time = 11.14, direction = "up"},
        {time = 11.85, direction = "down"},
        {time = 12.13, direction = "up"},
        {time = 12.42, direction = "down"},
        {time = 12.73, direction = "left"},
        {time = 13.03, direction = "right"},
        {time = 13.29, direction = "left"},
        {time = 13.98, direction = "up"},
        {time = 14.62, direction = "left"},
        {time = 15.21, direction = "up"},
        {time = 15.89, direction = "left"},

        -- 16-24 seconds
        -- Intense Pattern
        {time = 16.45, direction = "up"},
        {time = 17.09, direction = "left"},
        {time = 17.69, direction = "up"},
        {time = 18.26, direction = "right"},
        {time = 19.06, direction = "up"},
        {time = 19.40, direction = "left"},
        {time = 19.73, direction = "right"},
        {time = 20.02, direction = "left"},
        {time = 20.32, direction = "right"},
        {time = 20.61, direction = "left"},
        {time = 20.93, direction = "left"},
        {time = 21.25, direction = "left"},
        {time = 21.54, direction = "left"},
        {time = 21.83, direction = "right"},
        {time = 22.14, direction = "right"},
        {time = 22.48, direction = "left"},
        {time = 22.81, direction = "left"},
        {time = 23.13, direction = "right"},
        {time = 23.43, direction = "up"},
        {time = 23.80, direction = "down"},

        -- 24-32 seconds
        -- Intense Pattern
        {time = 24.14, direction = "left"},
        {time = 24.43, direction = "right"},
        {time = 24.73, direction = "left"},
        {time = 25.03, direction = "right"},
        {time = 25.35, direction = "left"},
        {time = 25.70, direction = "left"},
        {time = 26.00, direction = "left"},
        {time = 26.30, direction = "right"},
        {time = 26.61, direction = "right"},
        {time = 26.93, direction = "left"},
        {time = 27.27, direction = "left"},
        {time = 27.61, direction = "right"},
        {time = 27.92, direction = "right"},
        {time = 28.24, direction = "left"},
        {time = 28.53, direction = "left"},
        {time = 28.85, direction = "right"},
        {time = 29.16, direction = "right"},
        {time = 29.49, direction = "left"},
        {time = 29.78, direction = "left"},
        {time = 30.10, direction = "right"},
        {time = 30.41, direction = "right"},
        {time = 30.75, direction = "left"},
        {time = 31.03, direction = "left"},
        {time = 31.33, direction = "up"},
        {time = 31.66, direction = "down"},

        -- 32-40 seconds
        -- Intense Pattern
        {time = 32.00, direction = "left"},
        {time = 32.31, direction = "left"},
        {time = 32.63, direction = "right"},
        {time = 32.95, direction = "right"},
        {time = 33.29, direction = "left"},
        {time = 33.57, direction = "left"},
        {time = 33.89, direction = "right"},
        {time = 34.21, direction = "right"},
        {time = 34.53, direction = "left"},
        {time = 34.83, direction = "left"},
        {time = 35.15, direction = "right"},
        {time = 35.43, direction = "right"},
        {time = 35.76, direction = "up"},
        {time = 36.10, direction = "down"},
        {time = 36.79, direction = "up"},
        {time = 37.07, direction = "down"},
        {time = 37.37, direction = "left"},
        {time = 37.66, direction = "right"},
        {time = 38.03, direction = "left"},
        {time = 38.35, direction = "right"},
        {time = 38.68, direction = "left"},
        {time = 38.98, direction = "right"},
        {time = 39.29, direction = "left"},
        {time = 39.60, direction = "left"},
        {time = 39.90, direction = "left"},

        -- 40-48 seconds
        -- Intense Pattern
        {time = 40.22, direction = "right"},
        {time = 40.53, direction = "right"},
        {time = 40.83, direction = "left"},
        {time = 41.16, direction = "left"},
        {time = 41.46, direction = "up"},
        {time = 41.78, direction = "down"},
        {time = 42.13, direction = "up"},
        {time = 42.46, direction = "down"},
        {time = 42.77, direction = "left"},
        {time = 43.08, direction = "right"},
        {time = 43.42, direction = "left"},
        {time = 43.71, direction = "left"},
        {time = 44.01, direction = "right"},
        {time = 44.30, direction = "right"},
        {time = 44.62, direction = "left"},
        {time = 44.92, direction = "left"},
        {time = 45.22, direction = "right"},
        {time = 45.52, direction = "right"},
        {time = 45.87, direction = "left"},
        {time = 46.19, direction = "left"},
        {time = 46.52, direction = "right"},
        {time = 46.84, direction = "right"},
        {time = 47.17, direction = "left"},
        {time = 47.47, direction = "left"},
        {time = 47.79, direction = "right"},

        -- 48-56 seconds
        -- Intense Pattern
        {time = 48.09, direction = "right"},
        {time = 48.41, direction = "left"},
        {time = 48.74, direction = "left"},
        {time = 49.05, direction = "right"},
        {time = 49.38, direction = "right"},
        {time = 49.69, direction = "left"},
        {time = 50.03, direction = "right"},
        {time = 50.34, direction = "left"},
        {time = 50.64, direction = "right"},
        {time = 50.98, direction = "up"},
        {time = 51.28, direction = "down"},
        {time = 51.57, direction = "up"},
        {time = 52.21, direction = "left"},
        {time = 52.51, direction = "right"},
        {time = 52.85, direction = "up"},
        {time = 53.20, direction = "down"},
        {time = 53.49, direction = "up"},
        {time = 53.79, direction = "down"},
        {time = 54.07, direction = "left"},
        {time = 54.37, direction = "right"},
        {time = 54.71, direction = "left"},
        {time = 55.00, direction = "right"},
        {time = 55.34, direction = "left"},
        {time = 55.63, direction = "right"},
        {time = 55.96, direction = "up"},

        -- 56-64 seconds
        -- Intense Pattern
        {time = 56.30, direction = "down"},
        {time = 56.63, direction = "up"},
        {time = 56.92, direction = "down"},
        {time = 57.27, direction = "up"},
        {time = 57.56, direction = "down"},
        {time = 57.88, direction = "up"},
        {time = 58.17, direction = "down"},
        {time = 58.52, direction = "left"},
        {time = 58.81, direction = "right"},
        {time = 59.13, direction = "left"},
        {time = 59.43, direction = "right"},
        {time = 59.77, direction = "up"},
        {time = 60.07, direction = "down"},
        {time = 60.38, direction = "up"},
        {time = 60.69, direction = "down"},
        {time = 61.03, direction = "left"},
        {time = 61.36, direction = "left"},
        {time = 61.68, direction = "right"},
        {time = 61.99, direction = "right"},
        {time = 62.35, direction = "left"},
        {time = 62.63, direction = "left"},
        {time = 62.94, direction = "right"},
        {time = 63.24, direction = "right"},
        {time = 63.55, direction = "left"},
        {time = 63.83, direction = "left"},

        -- 64-72 seconds
        -- Intense Pattern
        {time = 64.17, direction = "right"},
        {time = 64.49, direction = "right"},
        {time = 64.82, direction = "left"},
        {time = 65.15, direction = "left"},
        {time = 65.46, direction = "right"},
        {time = 65.77, direction = "right"},
        {time = 66.09, direction = "up"},
        {time = 66.39, direction = "down"},
        {time = 66.73, direction = "up"},
        {time = 67.03, direction = "down"},
        {time = 67.37, direction = "up"},
        {time = 67.66, direction = "down"},
        {time = 67.99, direction = "up"},
        {time = 68.30, direction = "down"},
        {time = 68.65, direction = "left"},
        {time = 68.95, direction = "right"},
        {time = 69.28, direction = "left"},
        {time = 69.59, direction = "right"},
        {time = 69.90, direction = "up"},
        {time = 70.23, direction = "down"},
        {time = 70.56, direction = "up"},
        {time = 70.86, direction = "down"},
        {time = 71.18, direction = "left"},
        {time = 71.50, direction = "right"},
        {time = 71.83, direction = "left"},

        -- 72-80 seconds
        -- Intense Pattern
        {time = 72.17, direction = "right"},
        {time = 72.91, direction = "left"},
        {time = 73.26, direction = "left"},
        {time = 73.47, direction = "right"},
        {time = 73.68, direction = "right"},
        {time = 73.80, direction = "left"},
        {time = 73.97, direction = "right"},
        {time = 74.68, direction = "up"},
        {time = 75.02, direction = "down"},
        {time = 75.29, direction = "up"},
        {time = 75.58, direction = "down"},
        {time = 75.85, direction = "left"},
        {time = 76.13, direction = "right"},
        {time = 76.46, direction = "left"},
        {time = 77.21, direction = "left"},
        {time = 77.86, direction = "left"},
        {time = 78.50, direction = "left"},
        {time = 79.12, direction = "left"},
        {time = 79.69, direction = "right"},

        -- 80-88 seconds
        -- Intense Pattern
        {time = 80.36, direction = "right"},
        {time = 80.85, direction = "right"},
        {time = 81.48, direction = "left"},
        {time = 82.10, direction = "left"},
        {time = 82.76, direction = "left"},
        {time = 83.71, direction = "left"},
        {time = 84.35, direction = "right"},
        {time = 85.01, direction = "left"},
        {time = 85.64, direction = "left"},
        {time = 86.27, direction = "left"},
        {time = 86.78, direction = "left"},
        {time = 87.26, direction = "left"},
        {time = 87.59, direction = "left"},
        {time = 87.87, direction = "left"},

        -- 88-96 seconds
        -- Intense Pattern
        {time = 88.14, direction = "left"},
        {time = 88.46, direction = "left"},
        {time = 88.80, direction = "right"},
        {time = 89.13, direction = "right"},
        {time = 89.40, direction = "right"},
        {time = 89.71, direction = "right"},
        {time = 90.04, direction = "right"},
        {time = 90.33, direction = "right"},
        {time = 90.64, direction = "right"},
        {time = 90.93, direction = "right"},
        {time = 91.30, direction = "up"},
        {time = 91.63, direction = "up"},
        {time = 91.90, direction = "up"},
        {time = 92.20, direction = "down"},
        {time = 92.53, direction = "down"},
        {time = 92.84, direction = "down"},
        {time = 93.17, direction = "left"},
        {time = 93.49, direction = "left"},
        {time = 93.84, direction = "right"},
        {time = 94.16, direction = "right"},
        {time = 94.50, direction = "left"},
        {time = 94.81, direction = "left"},
        {time = 95.08, direction = "right"},
        {time = 95.44, direction = "right"},
        {time = 95.82, direction = "left"},

        -- 96-104 seconds
        -- Intense Pattern
        {time = 96.24, direction = "up"},
        {time = 96.60, direction = "down"},
        {time = 96.93, direction = "left"},
        {time = 97.24, direction = "right"},
        {time = 97.61, direction = "left"},
        {time = 98.20, direction = "up"},
        {time = 98.44, direction = "down"},
        {time = 98.83, direction = "left"},
        {time = 99.47, direction = "right"},
        {time = 100.10, direction = "left"},
        {time = 100.47, direction = "right"},
        {time = 100.79, direction = "left"},
        {time = 101.09, direction = "right"},
        {time = 101.42, direction = "left"},
        {time = 101.75, direction = "right"},
        {time = 102.07, direction = "left"},
        {time = 102.36, direction = "right"},
        {time = 102.71, direction = "left"},
        {time = 103.04, direction = "right"},
        {time = 103.35, direction = "left"},
        {time = 103.65, direction = "up"},
        {time = 103.97, direction = "down"},

        -- 104-112 seconds
        -- Intense Pattern
        {time = 104.29, direction = "up"},
        {time = 104.60, direction = "down"},
        {time = 104.93, direction = "up"},
        {time = 105.26, direction = "down"},
        {time = 105.58, direction = "up"},
        {time = 105.87, direction = "down"},
        {time = 106.19, direction = "up"},
        {time = 106.52, direction = "down"},
        {time = 106.81, direction = "up"},
        {time = 107.16, direction = "down"},
        {time = 107.47, direction = "up"},
        {time = 108.16, direction = "up"},
        {time = 108.45, direction = "down"},
        {time = 108.73, direction = "up"},
        {time = 109.02, direction = "left"},
        {time = 109.31, direction = "left"},
        {time = 109.62, direction = "left"},
        {time = 109.98, direction = "left"},
        {time = 110.30, direction = "right"},
        {time = 110.62, direction = "right"},
        {time = 110.94, direction = "right"},
        {time = 111.24, direction = "right"},
        {time = 111.57, direction = "up"},
        {time = 111.88, direction = "up"},

        -- 112-120 seconds
        -- Intense Pattern
        {time = 112.19, direction = "up"},
        {time = 112.48, direction = "up"},
        {time = 112.81, direction = "down"},
        {time = 113.16, direction = "down"},
        {time = 113.48, direction = "down"},
        {time = 113.79, direction = "down"},
        {time = 114.11, direction = "left"},
        {time = 114.79, direction = "left"},
        {time = 115.38, direction = "left"},
        {time = 115.99, direction = "left"},
        {time = 116.59, direction = "left"},
        {time = 117.26, direction = "left"},
        {time = 117.92, direction = "left"},
        {time = 118.54, direction = "left"},
        {time = 119.19, direction = "right"},
        {time = 119.80, direction = "right"},

        -- 120-128 seconds
        -- Intense Pattern
        {time = 120.43, direction = "right"},
        {time = 121.00, direction = "right"},
        {time = 121.71, direction = "up"},
        {time = 122.34, direction = "up"},
        {time = 122.97, direction = "down"},
        {time = 123.65, direction = "down"},
        {time = 124.31, direction = "left"},
        {time = 124.86, direction = "left"},
        {time = 125.44, direction = "left"},
        {time = 126.05, direction = "left"},
        {time = 126.72, direction = "left"},
        {time = 127.07, direction = "left"},
        {time = 127.37, direction = "right"},
        {time = 127.69, direction = "right"},

        -- 128-136 seconds
        -- Intense Pattern
        {time = 128.01, direction = "left"},
        {time = 128.33, direction = "left"},
        {time = 128.62, direction = "right"},
        {time = 129.27, direction = "left"},
        {time = 129.58, direction = "left"},
        {time = 129.90, direction = "right"},
        {time = 130.22, direction = "right"},
        {time = 130.53, direction = "left"},
        {time = 130.85, direction = "left"},
        {time = 131.16, direction = "right"},
        {time = 131.48, direction = "right"},
        {time = 132.13, direction = "left"},
        {time = 132.42, direction = "right"},
        {time = 132.74, direction = "right"},
        {time = 133.05, direction = "left"},
        {time = 133.37, direction = "left"},
        {time = 133.67, direction = "right"},
        {time = 133.98, direction = "right"},
        {time = 134.30, direction = "left"},
        {time = 134.61, direction = "left"},
        {time = 134.92, direction = "right"},
        {time = 135.25, direction = "right"},
        {time = 135.56, direction = "left"},
        {time = 135.88, direction = "left"},

        -- 136-144 seconds
        -- Intense Pattern
        {time = 136.18, direction = "right"},
        {time = 136.40, direction = "right"},
        {time = 136.55, direction = "left"},
        {time = 136.80, direction = "left"},
        {time = 136.94, direction = "right"},
        {time = 137.10, direction = "left"},
        {time = 137.26, direction = "right"},
        {time = 137.39, direction = "left"},
        {time = 137.59, direction = "right"},
        {time = 137.96, direction = "up"},
        {time = 138.34, direction = "down"},
        {time = 138.72, direction = "up"},
        {time = 139.06, direction = "down"},
        {time = 139.41, direction = "left"},
        {time = 139.69, direction = "left"},
        {time = 140.00, direction = "right"},
        {time = 140.33, direction = "left"},
        {time = 140.62, direction = "right"},
        {time = 140.94, direction = "left"},
        {time = 141.24, direction = "right"},
        {time = 141.58, direction = "left"},
        {time = 142.22, direction = "left"},
        {time = 142.53, direction = "right"},
        {time = 142.83, direction = "left"},
        {time = 143.14, direction = "right"},
        {time = 143.54, direction = "up"},
        {time = 143.85, direction = "down"},

        -- 144-152 seconds
        -- Intense Pattern
        {time = 144.23, direction = "down"},
        {time = 144.51, direction = "left"},
        {time = 144.78, direction = "right"},
        {time = 145.06, direction = "left"},
        {time = 145.35, direction = "right"},
        {time = 145.66, direction = "left"},
        {time = 145.97, direction = "right"},
        {time = 146.31, direction = "left"},
        {time = 146.63, direction = "right"},
        {time = 146.98, direction = "left"},
        {time = 147.29, direction = "left"},
        {time = 147.62, direction = "right"},
        {time = 147.93, direction = "left"},
        {time = 148.25, direction = "right"},
        {time = 148.95, direction = "left"},
        {time = 149.50, direction = "left"},
        {time = 150.06, direction = "left"},
        {time = 150.69, direction = "right"},
        {time = 151.41, direction = "right"},

        -- 152-160 seconds
        -- Intense Pattern
        {time = 152.38, direction = "left"},
        {time = 152.95, direction = "left"},
        {time = 153.56, direction = "left"},
        {time = 154.16, direction = "right"},
        {time = 154.84, direction = "right"},
        {time = 155.46, direction = "left"},
        {time = 156.12, direction = "left"},
        {time = 156.73, direction = "left"},
        {time = 157.35, direction = "left"},
        {time = 157.98, direction = "down"},
        {time = 158.31, direction = "up"},
        {time = 158.58, direction = "down"},
        {time = 158.92, direction = "up"},
        {time = 159.22, direction = "down"},
        {time = 159.58, direction = "left"},
        {time = 159.89, direction = "right"},

        -- 160-168 seconds
        -- Intense Pattern
        {time = 160.20, direction = "up"},
        {time = 160.41, direction = "down"},
        {time = 160.68, direction = "down"},
        {time = 160.79, direction = "left"},
        {time = 160.96, direction = "up"},
        {time = 161.16, direction = "right"},
        {time = 161.30, direction = "up"},
        {time = 161.46, direction = "right"},
        {time = 161.77, direction = "left"},
        {time = 162.11, direction = "left"},
        {time = 162.40, direction = "left"},
        {time = 162.71, direction = "right"},
        {time = 163.03, direction = "left"},
        {time = 163.37, direction = "left"},
        {time = 163.99, direction = "left"},
        {time = 164.30, direction = "right"},
        {time = 164.63, direction = "left"},
        {time = 165.28, direction = "left"},
        {time = 165.55, direction = "right"},
        {time = 165.88, direction = "left"},
        {time = 166.48, direction = "left"},
        {time = 166.79, direction = "right"},
        {time = 167.11, direction = "up"},
        {time = 167.42, direction = "down"},
        {time = 167.77, direction = "up"},

        -- 168-176 seconds
        -- Intense Pattern
        {time = 168.47, direction = "left"},
        {time = 169.00, direction = "right"},
        {time = 169.15, direction = "left"},
        {time = 169.62, direction = "left"},
        {time = 169.93, direction = "right"},
        {time = 170.31, direction = "left"},
        {time = 170.62, direction = "left"},
        {time = 170.95, direction = "right"},
        {time = 171.30, direction = "left"},
        {time = 171.60, direction = "right"},
        {time = 171.76, direction = "up"},
        {time = 171.91, direction = "left"},
        {time = 172.08, direction = "down"},
        {time = 172.23, direction = "right"},
        {time = 172.66, direction = "right"},
        {time = 172.96, direction = "left"},
        {time = 173.21, direction = "left"},
        {time = 173.76, direction = "left"},
        {time = 174.40, direction = "left"},
        {time = 175.02, direction = "left"},
        {time = 175.66, direction = "right"},

        -- 176-184 seconds
        -- Intense Pattern
        {time = 176.29, direction = "right"},
        {time = 176.91, direction = "right"},
        {time = 177.62, direction = "left"},
        {time = 178.21, direction = "right"},
        {time = 178.83, direction = "left"},
        {time = 179.43, direction = "right"},
        {time = 180.10, direction = "left"},
        {time = 180.79, direction = "right"},
        {time = 181.33, direction = "left"},
        {time = 181.57, direction = "right"},
        {time = 182.02, direction = "up"},
        {time = 182.31, direction = "down"},
        {time = 182.58, direction = "left"},
        {time = 182.97, direction = "right"},
        {time = 183.20, direction = "right"},
        {time = 183.55, direction = "right"},
        {time = 183.85, direction = "right"},

        -- 184-192 seconds
        -- Complex Sequence
        {time = 184.10, direction = "right"},
        {time = 184.47, direction = "left"},
        {time = 184.82, direction = "right"},
        {time = 185.17, direction = "right"},
        {time = 185.44, direction = "right"},
        {time = 185.61, direction = "right"},
        {time = 185.90, direction = "right"},
        {time = 186.22, direction = "right"},
        {time = 186.53, direction = "left"},
        {time = 186.74, direction = "left"},
        {time = 187.09, direction = "right"},
        {time = 187.39, direction = "right"}
    }
}