return {
    name = "La Gabbia Dorata",
    audio = "assets/La Gabbia Dorata.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 1.02, direction = "left"},
        {time = 1.89, direction = "right"},
        {time = 2.29, direction = "down"},
        {time = 2.66, direction = "up"},
        {time = 3.38, direction = "left"},
        {time = 4.06, direction = "right"},
        {time = 4.76, direction = "left"},
        {time = 5.35, direction = "right"},
        {time = 6.10, direction = "left"},
        {time = 6.46, direction = "right"},
        {time = 6.83, direction = "up"},
        {time = 7.17, direction = "down"},
        {time = 7.50, direction = "left"},
        {time = 7.82, direction = "right"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 8.23, direction = "left"},
        {time = 8.57, direction = "right"},
        {time = 8.94, direction = "up"},
        {time = 9.32, direction = "down"},
        {time = 9.68, direction = "left"},
        {time = 9.97, direction = "right"},
        {time = 10.30, direction = "left"},
        {time = 11.02, direction = "right"},
        {time = 11.70, direction = "left"},
        {time = 12.06, direction = "right"},
        {time = 12.39, direction = "left"},
        {time = 12.72, direction = "right"},
        {time = 13.05, direction = "up"},
        {time = 13.39, direction = "down"},
        {time = 13.76, direction = "left"},
        {time = 14.09, direction = "right"},
        {time = 14.47, direction = "left"},
        {time = 14.85, direction = "right"},
        {time = 15.20, direction = "left"},
        {time = 15.57, direction = "left"},
        {time = 15.89, direction = "right"},

        -- 16-24 seconds
        -- Intense Pattern
        {time = 16.26, direction = "left"},
        {time = 16.65, direction = "left"},
        {time = 16.97, direction = "left"},
        {time = 17.30, direction = "right"},
        {time = 17.63, direction = "right"},
        {time = 17.97, direction = "up"},
        {time = 18.29, direction = "down"},
        {time = 18.63, direction = "up"},
        {time = 18.98, direction = "down"},
        {time = 19.34, direction = "left"},
        {time = 19.71, direction = "right"},
        {time = 20.10, direction = "left"},
        {time = 20.83, direction = "right"},
        {time = 21.50, direction = "up"},
        {time = 21.79, direction = "down"},
        {time = 22.15, direction = "up"},
        {time = 22.47, direction = "down"},
        {time = 22.81, direction = "left"},
        {time = 23.20, direction = "right"},
        {time = 23.62, direction = "up"},
        {time = 23.95, direction = "down"},

        -- 24-32 seconds
        -- Intense Pattern
        {time = 24.24, direction = "left"},
        {time = 24.57, direction = "right"},
        {time = 24.95, direction = "left"},
        {time = 25.28, direction = "right"},
        {time = 25.65, direction = "left"},
        {time = 26.01, direction = "up"},
        {time = 26.51, direction = "down"},
        {time = 26.82, direction = "left"},
        {time = 27.10, direction = "right"},
        {time = 27.38, direction = "left"},
        {time = 27.71, direction = "right"},
        {time = 28.05, direction = "left"},
        {time = 28.38, direction = "right"},
        {time = 28.71, direction = "left"},
        {time = 29.42, direction = "down"},
        {time = 30.15, direction = "right"},
        {time = 30.89, direction = "down"},
        {time = 31.58, direction = "left"},

        -- 32-40 seconds
        -- Complex Sequence
        {time = 32.21, direction = "up"},
        {time = 32.97, direction = "right"},
        {time = 33.67, direction = "up"},
        {time = 34.39, direction = "down"},
        {time = 35.07, direction = "left"},
        {time = 35.73, direction = "down"},
        {time = 36.37, direction = "up"},
        {time = 37.12, direction = "left"},
        {time = 37.81, direction = "down"},
        {time = 38.52, direction = "left"},
        {time = 39.14, direction = "left"},
        {time = 39.99, direction = "right"},

        -- 40-48 seconds
        -- Intense Pattern
        {time = 40.97, direction = "left"},
        {time = 41.33, direction = "left"},
        {time = 41.69, direction = "right"},
        {time = 42.03, direction = "left"},
        {time = 42.38, direction = "up"},
        {time = 42.73, direction = "down"},
        {time = 43.09, direction = "left"},
        {time = 43.45, direction = "right"},
        {time = 43.80, direction = "left"},
        {time = 44.14, direction = "up"},
        {time = 44.50, direction = "down"},
        {time = 44.81, direction = "left"},
        {time = 45.18, direction = "right"},
        {time = 45.49, direction = "up"},
        {time = 45.84, direction = "down"},
        {time = 46.22, direction = "up"},
        {time = 46.94, direction = "right"},
        {time = 47.65, direction = "left"},

        -- 48-56 seconds
        -- Complex Sequence
        {time = 48.34, direction = "down"},
        {time = 49.05, direction = "left"},
        {time = 49.71, direction = "down"},
        {time = 50.38, direction = "left"},
        {time = 51.10, direction = "right"},
        {time = 51.80, direction = "up"},
        {time = 52.54, direction = "left"},
        {time = 53.17, direction = "right"},
        {time = 53.92, direction = "up"},
        {time = 54.61, direction = "down"},
        {time = 55.30, direction = "left"},

        -- 56-64 seconds
        -- Complex Sequence
        {time = 56.02, direction = "right"},
        {time = 56.72, direction = "up"},
        {time = 57.38, direction = "down"},
        {time = 58.09, direction = "left"},
        {time = 58.77, direction = "up"},
        {time = 59.44, direction = "right"},
        {time = 60.05, direction = "right"},
        {time = 60.79, direction = "down"},
        {time = 61.56, direction = "up"},
        {time = 62.30, direction = "down"},
        {time = 63.06, direction = "up"},
        {time = 63.71, direction = "down"},

        -- 64-72 seconds
        -- Complex Sequence
        {time = 64.53, direction = "left"},
        {time = 65.33, direction = "right"},
        {time = 66.05, direction = "left"},
        {time = 66.45, direction = "right"},
        {time = 67.11, direction = "up"},
        {time = 67.84, direction = "down"},
        {time = 68.53, direction = "up"},
        {time = 69.26, direction = "down"},
        {time = 69.96, direction = "up"},
        {time = 70.64, direction = "right"},
        {time = 71.60, direction = "left"},
        {time = 71.76, direction = "up"},

        -- 72-80 seconds
        -- Intense Pattern
        {time = 72.39, direction = "left"},
        {time = 72.74, direction = "up"},
        {time = 73.09, direction = "down"},
        {time = 73.41, direction = "right"},
        {time = 73.77, direction = "left"},
        {time = 74.12, direction = "up"},
        {time = 74.45, direction = "down"},
        {time = 74.80, direction = "left"},
        {time = 75.16, direction = "up"},
        {time = 75.53, direction = "right"},
        {time = 75.85, direction = "left"},
        {time = 76.21, direction = "right"},
        {time = 76.57, direction = "left"},
        {time = 76.98, direction = "up"},
        {time = 77.29, direction = "down"},
        {time = 77.94, direction = "left"},
        {time = 78.61, direction = "down"},
        {time = 79.33, direction = "left"},

        -- 80-88 seconds
        -- Intense Pattern
        {time = 80.07, direction = "left"},
        {time = 80.73, direction = "down"},
        {time = 81.41, direction = "up"},
        {time = 82.15, direction = "down"},
        {time = 82.86, direction = "up"},
        {time = 83.53, direction = "down"},
        {time = 83.89, direction = "up"},
        {time = 84.22, direction = "left"},
        {time = 84.57, direction = "right"},
        {time = 84.93, direction = "up"},
        {time = 85.22, direction = "down"},
        {time = 85.66, direction = "left"},
        {time = 85.98, direction = "right"},
        {time = 86.31, direction = "up"},
        {time = 86.75, direction = "down"},
        {time = 87.11, direction = "left"},
        {time = 87.36, direction = "right"},
        {time = 87.74, direction = "up"},

        -- 88-96 seconds
        -- Intense Pattern
        {time = 88.06, direction = "down"},
        {time = 88.46, direction = "left"},
        {time = 88.76, direction = "right"},
        {time = 89.11, direction = "up"},
        {time = 89.44, direction = "left"},
        {time = 89.80, direction = "right"},
        {time = 90.17, direction = "up"},
        {time = 90.54, direction = "down"},
        {time = 90.90, direction = "left"},
        {time = 91.26, direction = "up"},
        {time = 91.88, direction = "down"},
        {time = 92.55, direction = "left"},
        {time = 93.18, direction = "down"},
        {time = 93.93, direction = "left"},
        {time = 94.62, direction = "right"},
        {time = 95.35, direction = "up"},

        -- 96-104 seconds
        -- Intense Pattern
        {time = 96.13, direction = "left"},
        {time = 96.45, direction = "right"},
        {time = 96.78, direction = "up"},
        {time = 97.10, direction = "down"},
        {time = 97.46, direction = "left"},
        {time = 97.78, direction = "up"},
        {time = 98.23, direction = "right"},
        {time = 98.54, direction = "left"},
        {time = 98.86, direction = "right"},
        {time = 99.61, direction = "down"},
        {time = 100.30, direction = "left"},
        {time = 100.98, direction = "right"},
        {time = 101.67, direction = "left"},
        {time = 102.35, direction = "down"},
        {time = 103.08, direction = "left"},
        {time = 103.78, direction = "down"},

        -- 104-112 seconds
        -- Complex Sequence
        {time = 104.43, direction = "up"},
        {time = 105.17, direction = "left"},
        {time = 105.85, direction = "down"},
        {time = 106.57, direction = "left"},
        {time = 107.27, direction = "down"},
        {time = 107.99, direction = "left"},
        {time = 108.69, direction = "down"},
        {time = 109.35, direction = "left"},
        {time = 110.05, direction = "down"},
        {time = 110.69, direction = "left"},
        {time = 111.43, direction = "right"},
        {time = 111.77, direction = "left"},

        -- 112-120 seconds
        -- Intense Pattern
        {time = 112.15, direction = "up"},
        {time = 112.49, direction = "down"},
        {time = 112.82, direction = "left"},
        {time = 113.17, direction = "right"},
        {time = 113.50, direction = "up"},
        {time = 114.15, direction = "left"},
        {time = 114.95, direction = "down"},
        {time = 115.59, direction = "left"},
        {time = 116.35, direction = "left"},
        {time = 116.73, direction = "right"},
        {time = 117.09, direction = "up"},
        {time = 117.40, direction = "down"},
        {time = 117.79, direction = "left"},
        {time = 118.06, direction = "right"},
        {time = 118.45, direction = "up"},
        {time = 118.75, direction = "down"},
        {time = 119.10, direction = "left"},
        {time = 119.44, direction = "right"},
        {time = 119.83, direction = "up"},

        -- 120-128 seconds
        -- Intense Pattern
        {time = 120.59, direction = "left"},
        {time = 121.22, direction = "down"},
        {time = 121.90, direction = "left"},
        {time = 122.55, direction = "left"},
        {time = 122.91, direction = "right"},
        {time = 123.29, direction = "up"},
        {time = 123.63, direction = "down"},
        {time = 124.00, direction = "left"},
        {time = 124.32, direction = "right"},
        {time = 124.66, direction = "up"},
        {time = 125.03, direction = "down"},
        {time = 125.36, direction = "left"},
        {time = 125.73, direction = "right"},
        {time = 126.11, direction = "up"},
        {time = 126.45, direction = "down"},
        {time = 126.86, direction = "left"},
        {time = 127.18, direction = "right"},
        {time = 127.49, direction = "up"},
        {time = 127.79, direction = "down"},

        -- 128-136 seconds
        -- Intense Pattern
        {time = 128.11, direction = "left"},
        {time = 128.51, direction = "right"},
        {time = 128.90, direction = "left"},
        {time = 129.25, direction = "right"},
        {time = 129.60, direction = "left"},
        {time = 129.91, direction = "right"},
        {time = 130.29, direction = "up"},
        {time = 130.62, direction = "down"},
        {time = 130.95, direction = "left"},
        {time = 131.27, direction = "right"},
        {time = 131.63, direction = "up"},
        {time = 131.97, direction = "down"},
        {time = 132.35, direction = "up"},
        {time = 132.69, direction = "down"},
        {time = 133.01, direction = "left"},
        {time = 133.36, direction = "right"},
        {time = 133.71, direction = "up"},
        {time = 134.06, direction = "down"},
        {time = 134.41, direction = "left"},
        {time = 134.76, direction = "right"},
        {time = 135.15, direction = "up"},
        {time = 135.43, direction = "down"},
        {time = 135.85, direction = "up"},

        -- 136-144 seconds
        -- Intense Pattern
        {time = 136.56, direction = "down"},
        {time = 137.28, direction = "up"},
        {time = 137.95, direction = "down"},
        {time = 138.63, direction = "left"},
        {time = 139.04, direction = "right"},
        {time = 139.53, direction = "up"},
        {time = 140.09, direction = "down"},
        {time = 140.79, direction = "left"},
        {time = 141.43, direction = "down"},
        {time = 142.07, direction = "left"},
        {time = 142.79, direction = "down"},
        {time = 143.37, direction = "left"},
        {time = 143.75, direction = "up"},

        -- 144-152 seconds
        -- Intense Pattern
        {time = 144.12, direction = "down"},
        {time = 144.51, direction = "up"},
        {time = 144.84, direction = "left"},
        {time = 145.29, direction = "right"},
        {time = 145.66, direction = "up"},
        {time = 146.01, direction = "down"},
        {time = 146.33, direction = "left"},
        {time = 146.70, direction = "up"},
        {time = 147.05, direction = "right"},
        {time = 147.46, direction = "down"},
        {time = 147.80, direction = "left"},
        {time = 148.11, direction = "up"},
        {time = 148.44, direction = "right"},
        {time = 148.73, direction = "down"},
        {time = 149.10, direction = "left"},
        {time = 149.43, direction = "up"},
        {time = 149.79, direction = "right"},
        {time = 150.10, direction = "down"},
        {time = 150.46, direction = "left"},
        {time = 150.81, direction = "up"},
        {time = 151.14, direction = "right"},
        {time = 151.54, direction = "down"},
        {time = 151.93, direction = "left"},

        -- 152-160 seconds
        -- Complex Sequence
        {time = 152.19, direction = "up"},
        {time = 152.53, direction = "right"},
        {time = 152.93, direction = "down"},
        {time = 153.61, direction = "up"},
        {time = 153.94, direction = "right"},
        {time = 154.39, direction = "down"},
        {time = 154.70, direction = "left"},
        {time = 155.00, direction = "up"},
        {time = 155.31, direction = "right"},
        {time = 155.72, direction = "right"}
    }
}