return {
    name = "Il Gioco Invisibile",
    audio = "assets/Il Gioco Invisibile.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 0.93, direction = "left"},
        {time = 1.60, direction = "right"},
        {time = 2.21, direction = "left"},
        {time = 2.89, direction = "right"},
        {time = 3.65, direction = "left"},
        {time = 4.38, direction = "right"},
        {time = 5.21, direction = "down"},
        {time = 5.96, direction = "up"},
        {time = 6.28, direction = "left"},
        {time = 6.71, direction = "right"},
        {time = 7.10, direction = "left"},
        {time = 7.47, direction = "right"},
        {time = 7.87, direction = "up"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 8.25, direction = "down"},
        {time = 8.61, direction = "left"},
        {time = 8.96, direction = "right"},
        {time = 9.35, direction = "up"},
        {time = 9.70, direction = "down"},
        {time = 10.07, direction = "left"},
        {time = 10.42, direction = "right"},
        {time = 10.80, direction = "up"},
        {time = 11.17, direction = "down"},
        {time = 11.54, direction = "left"},
        {time = 11.91, direction = "right"},
        {time = 12.31, direction = "up"},
        {time = 12.66, direction = "down"},
        {time = 13.07, direction = "left"},
        {time = 13.45, direction = "right"},
        {time = 13.84, direction = "left"},
        {time = 14.22, direction = "right"},
        {time = 14.61, direction = "left"},
        {time = 14.96, direction = "right"},
        {time = 15.32, direction = "up"},
        {time = 15.70, direction = "down"},

        -- 16-24 seconds
        -- Intense Pattern
        {time = 16.09, direction = "up"},
        {time = 16.43, direction = "down"},
        {time = 16.82, direction = "up"},
        {time = 17.19, direction = "down"},
        {time = 17.58, direction = "left"},
        {time = 17.95, direction = "right"},
        {time = 18.32, direction = "up"},
        {time = 18.69, direction = "down"},
        {time = 19.07, direction = "up"},
        {time = 19.37, direction = "down"},
        {time = 19.79, direction = "left"},
        {time = 20.18, direction = "right"},
        {time = 20.52, direction = "up"},
        {time = 20.87, direction = "down"},
        {time = 21.29, direction = "left"},
        {time = 21.66, direction = "right"},
        {time = 22.05, direction = "up"},
        {time = 22.42, direction = "down"},
        {time = 22.81, direction = "right"},
        {time = 23.20, direction = "left"},
        {time = 23.59, direction = "right"},
        {time = 23.97, direction = "up"},

        -- 24-32 seconds
        -- Intense Pattern
        {time = 24.29, direction = "down"},
        {time = 24.67, direction = "up"},
        {time = 25.05, direction = "left"},
        {time = 25.44, direction = "right"},
        {time = 25.79, direction = "up"},
        {time = 26.14, direction = "down"},
        {time = 26.58, direction = "left"},
        {time = 26.91, direction = "right"},
        {time = 27.33, direction = "up"},
        {time = 27.68, direction = "down"},
        {time = 28.07, direction = "left"},
        {time = 28.43, direction = "right"},
        {time = 28.76, direction = "up"},
        {time = 29.12, direction = "down"},
        {time = 29.53, direction = "left"},
        {time = 29.87, direction = "right"},
        {time = 30.28, direction = "up"},
        {time = 30.66, direction = "left"},
        {time = 31.02, direction = "right"},
        {time = 31.40, direction = "up"},
        {time = 31.78, direction = "left"},

        -- 32-40 seconds
        -- Intense Pattern
        {time = 32.13, direction = "right"},
        {time = 32.53, direction = "up"},
        {time = 32.86, direction = "down"},
        {time = 33.22, direction = "left"},
        {time = 33.65, direction = "right"},
        {time = 34.03, direction = "up"},
        {time = 34.39, direction = "down"},
        {time = 34.78, direction = "left"},
        {time = 35.20, direction = "right"},
        {time = 35.62, direction = "up"},
        {time = 35.95, direction = "down"},
        {time = 36.36, direction = "left"},
        {time = 36.72, direction = "up"},
        {time = 37.07, direction = "down"},
        {time = 37.44, direction = "right"},
        {time = 37.82, direction = "left"},
        {time = 38.22, direction = "right"},
        {time = 38.60, direction = "left"},
        {time = 38.98, direction = "right"},
        {time = 39.34, direction = "up"},
        {time = 39.71, direction = "down"},

        -- 40-48 seconds
        -- Intense Pattern
        {time = 40.09, direction = "up"},
        {time = 40.43, direction = "down"},
        {time = 40.82, direction = "left"},
        {time = 41.21, direction = "right"},
        {time = 41.60, direction = "left"},
        {time = 41.98, direction = "right"},
        {time = 42.33, direction = "left"},
        {time = 42.71, direction = "right"},
        {time = 43.10, direction = "up"},
        {time = 43.43, direction = "down"},
        {time = 43.82, direction = "left"},
        {time = 44.23, direction = "right"},
        {time = 44.62, direction = "left"},
        {time = 44.99, direction = "right"},
        {time = 45.34, direction = "up"},
        {time = 45.69, direction = "down"},
        {time = 46.10, direction = "left"},
        {time = 46.47, direction = "right"},
        {time = 46.83, direction = "left"},
        {time = 47.23, direction = "right"},
        {time = 47.62, direction = "left"},
        {time = 47.94, direction = "right"},

        -- 48-56 seconds
        -- Intense Pattern
        {time = 48.35, direction = "down"},
        {time = 49.09, direction = "left"},
        {time = 49.81, direction = "down"},
        {time = 50.51, direction = "left"},
        {time = 51.35, direction = "left"},
        {time = 51.72, direction = "right"},
        {time = 52.10, direction = "left"},
        {time = 52.46, direction = "right"},
        {time = 52.84, direction = "up"},
        {time = 53.14, direction = "down"},
        {time = 53.55, direction = "left"},
        {time = 53.90, direction = "right"},
        {time = 54.29, direction = "up"},
        {time = 54.64, direction = "down"},
        {time = 54.99, direction = "left"},
        {time = 55.38, direction = "up"},
        {time = 55.78, direction = "right"},

        -- 56-64 seconds
        -- Intense Pattern
        {time = 56.18, direction = "down"},
        {time = 56.54, direction = "left"},
        {time = 56.93, direction = "up"},
        {time = 57.33, direction = "right"},
        {time = 57.69, direction = "left"},
        {time = 58.05, direction = "up"},
        {time = 58.46, direction = "down"},
        {time = 58.81, direction = "right"},
        {time = 59.16, direction = "left"},
        {time = 59.54, direction = "up"},
        {time = 59.92, direction = "down"},
        {time = 60.30, direction = "up"},
        {time = 60.67, direction = "right"},
        {time = 61.04, direction = "left"},
        {time = 61.40, direction = "up"},
        {time = 61.77, direction = "down"},
        {time = 62.13, direction = "right"},
        {time = 62.53, direction = "left"},
        {time = 62.91, direction = "right"},
        {time = 63.25, direction = "up"},
        {time = 63.62, direction = "down"},

        -- 64-72 seconds
        -- Intense Pattern
        {time = 64.02, direction = "left"},
        {time = 64.37, direction = "right"},
        {time = 64.80, direction = "left"},
        {time = 65.19, direction = "right"},
        {time = 65.59, direction = "up"},
        {time = 65.98, direction = "down"},
        {time = 66.36, direction = "left"},
        {time = 66.47, direction = "up"},
        {time = 67.08, direction = "right"},
        {time = 67.85, direction = "left"},
        {time = 68.23, direction = "right"},
        {time = 68.61, direction = "up"},
        {time = 68.97, direction = "down"},
        {time = 69.32, direction = "left"},
        {time = 69.69, direction = "right"},
        {time = 70.18, direction = "up"},
        {time = 70.50, direction = "down"},
        {time = 70.86, direction = "left"},
        {time = 71.20, direction = "right"},
        {time = 71.60, direction = "up"},
        {time = 71.99, direction = "down"},

        -- 72-80 seconds
        -- Intense Pattern
        {time = 72.64, direction = "up"},
        {time = 73.06, direction = "down"},
        {time = 73.40, direction = "left"},
        {time = 73.75, direction = "right"},
        {time = 74.18, direction = "left"},
        {time = 74.58, direction = "right"},
        {time = 74.97, direction = "up"},
        {time = 75.38, direction = "down"},
        {time = 75.74, direction = "up"},
        {time = 76.10, direction = "down"},
        {time = 76.45, direction = "left"},
        {time = 76.83, direction = "right"},
        {time = 77.16, direction = "up"},
        {time = 77.55, direction = "down"},
        {time = 77.86, direction = "left"},
        {time = 78.27, direction = "up"},
        {time = 79.02, direction = "down"},
        {time = 79.80, direction = "up"},

        -- 80-88 seconds
        -- Intense Pattern
        {time = 80.60, direction = "down"},
        {time = 81.33, direction = "left"},
        {time = 82.09, direction = "down"},
        {time = 82.79, direction = "up"},
        {time = 83.57, direction = "down"},
        {time = 84.31, direction = "left"},
        {time = 84.70, direction = "right"},
        {time = 85.08, direction = "left"},
        {time = 85.45, direction = "right"},
        {time = 85.83, direction = "left"},
        {time = 86.23, direction = "right"},
        {time = 87.00, direction = "left"},
        {time = 87.36, direction = "right"},
        {time = 87.70, direction = "left"},

        -- 88-96 seconds
        -- Intense Pattern
        {time = 88.07, direction = "right"},
        {time = 88.44, direction = "left"},
        {time = 88.82, direction = "right"},
        {time = 89.17, direction = "up"},
        {time = 89.55, direction = "down"},
        {time = 89.92, direction = "left"},
        {time = 90.30, direction = "right"},
        {time = 91.04, direction = "left"},
        {time = 91.81, direction = "left"},
        {time = 92.59, direction = "left"},
        {time = 93.36, direction = "right"},
        {time = 94.10, direction = "left"},
        {time = 94.45, direction = "right"},
        {time = 94.97, direction = "up"},
        {time = 95.67, direction = "down"},

        -- 96-104 seconds
        -- Intense Pattern
        {time = 96.38, direction = "left"},
        {time = 96.74, direction = "right"},
        {time = 97.15, direction = "left"},
        {time = 97.49, direction = "right"},
        {time = 97.89, direction = "left"},
        {time = 98.26, direction = "right"},
        {time = 98.60, direction = "left"},
        {time = 98.98, direction = "right"},
        {time = 99.35, direction = "up"},
        {time = 99.73, direction = "down"},
        {time = 100.11, direction = "left"},
        {time = 100.49, direction = "right"},
        {time = 100.87, direction = "left"},
        {time = 101.22, direction = "right"},
        {time = 101.58, direction = "left"},
        {time = 101.97, direction = "down"},
        {time = 102.37, direction = "down"},
        {time = 102.73, direction = "left"},
        {time = 103.12, direction = "right"},
        {time = 103.46, direction = "up"},

        -- 104-112 seconds
        -- Intense Pattern
        {time = 104.20, direction = "left"},
        {time = 104.60, direction = "right"},
        {time = 104.96, direction = "left"},
        {time = 105.35, direction = "up"},
        {time = 105.70, direction = "down"},
        {time = 106.09, direction = "left"},
        {time = 106.44, direction = "right"},
        {time = 106.78, direction = "up"},
        {time = 107.17, direction = "down"},
        {time = 107.56, direction = "left"},
        {time = 107.96, direction = "right"},
        {time = 108.35, direction = "up"},
        {time = 108.73, direction = "down"},
        {time = 109.11, direction = "left"},
        {time = 109.46, direction = "right"},
        {time = 109.81, direction = "left"},
        {time = 110.21, direction = "right"},
        {time = 110.58, direction = "up"},
        {time = 110.95, direction = "down"},
        {time = 111.32, direction = "left"},
        {time = 111.69, direction = "right"},

        -- 112-120 seconds
        -- Intense Pattern
        {time = 112.08, direction = "up"},
        {time = 112.46, direction = "down"},
        {time = 112.85, direction = "left"},
        {time = 113.19, direction = "right"},
        {time = 113.60, direction = "up"},
        {time = 113.92, direction = "down"},
        {time = 114.31, direction = "left"},
        {time = 114.70, direction = "right"},
        {time = 115.11, direction = "left"},
        {time = 115.46, direction = "right"},
        {time = 115.80, direction = "up"},
        {time = 116.16, direction = "down"},
        {time = 116.54, direction = "left"},
        {time = 116.88, direction = "right"},
        {time = 117.28, direction = "up"},
        {time = 117.65, direction = "down"},
        {time = 118.06, direction = "left"},
        {time = 118.45, direction = "right"},
        {time = 118.83, direction = "left"},
        {time = 119.48, direction = "right"},
        {time = 119.87, direction = "up"},

        -- 120-128 seconds
        -- Intense Pattern
        {time = 120.18, direction = "down"},
        {time = 120.53, direction = "left"},
        {time = 120.85, direction = "right"},
        {time = 121.13, direction = "up"},
        {time = 121.41, direction = "down"},
        {time = 121.78, direction = "left"},
        {time = 122.11, direction = "right"},
        {time = 122.57, direction = "up"},
        {time = 122.87, direction = "down"},
        {time = 123.29, direction = "left"},
        {time = 123.68, direction = "right"},
        {time = 124.11, direction = "up"},
        {time = 124.43, direction = "down"},
        {time = 124.80, direction = "left"},
        {time = 125.14, direction = "right"},
        {time = 125.59, direction = "left"},
        {time = 125.95, direction = "right"},
        {time = 126.31, direction = "left"},
        {time = 126.68, direction = "right"},
        {time = 127.06, direction = "up"},
        {time = 127.41, direction = "down"},
        {time = 127.81, direction = "left"},

        -- 128-136 seconds
        -- Intense Pattern
        {time = 128.16, direction = "right"},
        {time = 128.58, direction = "up"},
        {time = 128.89, direction = "down"},
        {time = 129.25, direction = "left"},
        {time = 129.66, direction = "right"},
        {time = 130.00, direction = "left"},
        {time = 130.39, direction = "right"},
        {time = 130.74, direction = "up"},
        {time = 131.10, direction = "down"},
        {time = 131.51, direction = "left"},
        {time = 131.93, direction = "right"},
        {time = 132.30, direction = "down"},
        {time = 132.69, direction = "up"},
        {time = 133.05, direction = "left"},
        {time = 133.46, direction = "right"},
        {time = 133.86, direction = "left"},
        {time = 134.23, direction = "right"},
        {time = 134.62, direction = "left"},
        {time = 134.95, direction = "right"},
        {time = 135.73, direction = "left"},

        -- 136-144 seconds
        -- Intense Pattern
        {time = 136.07, direction = "right"},
        {time = 136.42, direction = "left"},
        {time = 136.81, direction = "right"},
        {time = 137.15, direction = "left"},
        {time = 137.54, direction = "right"},
        {time = 137.94, direction = "left"},
        {time = 138.33, direction = "right"},
        {time = 138.71, direction = "left"},
        {time = 139.10, direction = "right"},
        {time = 139.48, direction = "left"},
        {time = 139.84, direction = "right"},
        {time = 140.21, direction = "left"},
        {time = 140.57, direction = "right"},
        {time = 140.94, direction = "left"},
        {time = 141.31, direction = "right"},
        {time = 141.68, direction = "up"},
        {time = 142.05, direction = "down"},
        {time = 142.43, direction = "left"},
        {time = 142.80, direction = "right"},
        {time = 143.18, direction = "left"},
        {time = 143.58, direction = "right"},
        {time = 143.95, direction = "up"},

        -- 144-152 seconds
        -- Intense Pattern
        {time = 144.27, direction = "down"},
        {time = 144.68, direction = "left"},
        {time = 145.07, direction = "right"},
        {time = 145.47, direction = "up"},
        {time = 145.82, direction = "down"},
        {time = 146.22, direction = "left"},
        {time = 146.57, direction = "up"},
        {time = 146.88, direction = "down"},
        {time = 147.33, direction = "left"},
        {time = 147.69, direction = "up"},
        {time = 148.05, direction = "down"},
        {time = 148.40, direction = "right"},
        {time = 148.85, direction = "left"},
        {time = 149.18, direction = "right"},
        {time = 149.59, direction = "up"},
        {time = 149.91, direction = "down"},
        {time = 150.30, direction = "left"},
        {time = 150.66, direction = "up"},
        {time = 150.97, direction = "down"},
        {time = 151.39, direction = "left"},
        {time = 151.78, direction = "right"},

        -- 152-160 seconds
        -- Simple Sequence
        {time = 152.19, direction = "left"},
        {time = 152.78, direction = "down"},
        {time = 153.65, direction = "left"},
        {time = 154.41, direction = "down"}
    }
}