return {
    name = "Digital Dreams∞Infinity",
    audio = "assets/Digital Dreams∞Infinity.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 1.13, direction = "left"},
        {time = 1.69, direction = "right"},
        {time = 2.29, direction = "down"},
        {time = 2.99, direction = "left"},
        {time = 3.66, direction = "right"},
        {time = 4.32, direction = "left"},
        {time = 4.86, direction = "right"},
        {time = 5.37, direction = "left"},
        {time = 5.80, direction = "up"},
        {time = 6.17, direction = "down"},
        {time = 6.58, direction = "left"},
        {time = 6.95, direction = "right"},
        {time = 7.33, direction = "left"},
        {time = 7.75, direction = "right"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 8.06, direction = "left"},
        {time = 8.44, direction = "right"},
        {time = 8.83, direction = "left"},
        {time = 9.18, direction = "right"},
        {time = 9.57, direction = "left"},
        {time = 9.91, direction = "up"},
        {time = 10.31, direction = "down"},
        {time = 10.67, direction = "left"},
        {time = 11.06, direction = "right"},
        {time = 11.41, direction = "left"},
        {time = 11.79, direction = "right"},
        {time = 12.17, direction = "up"},
        {time = 12.54, direction = "down"},
        {time = 12.91, direction = "left"},
        {time = 13.26, direction = "right"},
        {time = 13.65, direction = "left"},
        {time = 14.01, direction = "right"},
        {time = 14.38, direction = "left"},
        {time = 14.76, direction = "right"},
        {time = 15.12, direction = "left"},
        {time = 15.50, direction = "right"},
        {time = 15.87, direction = "up"},

        -- 16-24 seconds
        -- Intense Pattern
        {time = 16.57, direction = "down"},
        {time = 16.94, direction = "up"},
        {time = 17.34, direction = "left"},
        {time = 17.72, direction = "right"},
        {time = 18.10, direction = "left"},
        {time = 18.48, direction = "right"},
        {time = 18.87, direction = "up"},
        {time = 19.23, direction = "down"},
        {time = 19.58, direction = "left"},
        {time = 19.94, direction = "right"},
        {time = 20.31, direction = "left"},
        {time = 20.66, direction = "right"},
        {time = 21.02, direction = "left"},
        {time = 21.41, direction = "left"},
        {time = 21.77, direction = "right"},
        {time = 22.14, direction = "right"},
        {time = 22.51, direction = "up"},
        {time = 22.88, direction = "up"},
        {time = 23.25, direction = "down"},
        {time = 23.66, direction = "down"},
        {time = 23.97, direction = "left"},

        -- 24-32 seconds
        -- Intense Pattern
        {time = 24.36, direction = "right"},
        {time = 24.72, direction = "left"},
        {time = 25.09, direction = "left"},
        {time = 25.43, direction = "right"},
        {time = 25.83, direction = "right"},
        {time = 26.19, direction = "left"},
        {time = 26.59, direction = "left"},
        {time = 26.97, direction = "up"},
        {time = 27.34, direction = "up"},
        {time = 27.69, direction = "left"},
        {time = 28.43, direction = "right"},
        {time = 28.54, direction = "up"},
        {time = 29.24, direction = "left"},
        {time = 30.01, direction = "down"},
        {time = 30.66, direction = "left"},
        {time = 31.47, direction = "down"},

        -- 32-40 seconds
        -- Intense Pattern
        {time = 32.13, direction = "right"},
        {time = 32.87, direction = "left"},
        {time = 33.62, direction = "right"},
        {time = 34.38, direction = "down"},
        {time = 35.10, direction = "up"},
        {time = 35.82, direction = "left"},
        {time = 36.19, direction = "right"},
        {time = 36.59, direction = "left"},
        {time = 36.98, direction = "left"},
        {time = 37.35, direction = "right"},
        {time = 37.69, direction = "left"},
        {time = 38.05, direction = "right"},
        {time = 38.44, direction = "left"},
        {time = 38.79, direction = "up"},
        {time = 39.11, direction = "down"},
        {time = 39.47, direction = "left"},

        -- 40-48 seconds
        -- Intense Pattern
        {time = 40.25, direction = "up"},
        {time = 40.66, direction = "down"},
        {time = 40.99, direction = "right"},
        {time = 41.77, direction = "left"},
        {time = 42.53, direction = "right"},
        {time = 43.30, direction = "up"},
        {time = 43.99, direction = "down"},
        {time = 44.71, direction = "left"},
        {time = 45.42, direction = "right"},
        {time = 46.18, direction = "left"},
        {time = 46.55, direction = "right"},
        {time = 46.95, direction = "up"},
        {time = 47.33, direction = "down"},
        {time = 47.71, direction = "left"},

        -- 48-56 seconds
        -- Intense Pattern
        {time = 48.07, direction = "right"},
        {time = 48.43, direction = "up"},
        {time = 48.81, direction = "down"},
        {time = 49.17, direction = "left"},
        {time = 49.53, direction = "right"},
        {time = 49.89, direction = "left"},
        {time = 50.25, direction = "right"},
        {time = 50.64, direction = "left"},
        {time = 51.01, direction = "right"},
        {time = 51.39, direction = "right"},
        {time = 51.79, direction = "up"},
        {time = 52.14, direction = "down"},
        {time = 52.50, direction = "left"},
        {time = 52.85, direction = "right"},
        {time = 53.26, direction = "up"},
        {time = 53.59, direction = "down"},
        {time = 53.95, direction = "right"},
        {time = 54.33, direction = "up"},
        {time = 54.69, direction = "down"},
        {time = 55.05, direction = "left"},
        {time = 55.46, direction = "up"},
        {time = 55.83, direction = "down"},

        -- 56-64 seconds
        -- Intense Pattern
        {time = 56.17, direction = "left"},
        {time = 56.54, direction = "right"},
        {time = 56.93, direction = "left"},
        {time = 57.31, direction = "up"},
        {time = 57.65, direction = "down"},
        {time = 58.01, direction = "left"},
        {time = 58.38, direction = "right"},
        {time = 59.17, direction = "down"},
        {time = 59.59, direction = "left"},
        {time = 59.93, direction = "right"},
        {time = 60.29, direction = "left"},
        {time = 60.66, direction = "right"},
        {time = 61.03, direction = "left"},
        {time = 61.41, direction = "left"},
        {time = 61.80, direction = "right"},
        {time = 62.18, direction = "right"},
        {time = 62.58, direction = "left"},
        {time = 62.90, direction = "right"},
        {time = 63.28, direction = "left"},
        {time = 63.63, direction = "up"},
        {time = 63.98, direction = "down"},

        -- 64-72 seconds
        -- Complex Sequence
        {time = 64.28, direction = "left"},
        {time = 64.62, direction = "up"},
        {time = 65.44, direction = "right"},
        {time = 66.25, direction = "left"},
        {time = 66.94, direction = "right"},
        {time = 67.71, direction = "right"},
        {time = 68.53, direction = "up"},
        {time = 69.22, direction = "down"},
        {time = 69.93, direction = "right"},
        {time = 70.67, direction = "down"},
        {time = 71.43, direction = "right"},

        -- 72-80 seconds
        -- Intense Pattern
        {time = 72.10, direction = "left"},
        {time = 72.87, direction = "right"},
        {time = 73.57, direction = "left"},
        {time = 73.95, direction = "left"},
        {time = 74.37, direction = "right"},
        {time = 74.71, direction = "left"},
        {time = 75.08, direction = "right"},
        {time = 75.47, direction = "left"},
        {time = 76.15, direction = "left"},
        {time = 76.89, direction = "right"},
        {time = 77.65, direction = "up"},
        {time = 78.44, direction = "down"},
        {time = 79.19, direction = "left"},
        {time = 79.94, direction = "right"},

        -- 80-88 seconds
        -- Complex Sequence
        {time = 81.41, direction = "left"},
        {time = 82.13, direction = "down"},
        {time = 82.90, direction = "up"},
        {time = 83.64, direction = "left"},
        {time = 84.36, direction = "right"},
        {time = 85.08, direction = "left"},
        {time = 85.83, direction = "right"},
        {time = 86.61, direction = "right"},
        {time = 87.34, direction = "right"},

        -- 88-96 seconds
        -- Complex Sequence
        {time = 88.07, direction = "right"},
        {time = 88.84, direction = "right"},
        {time = 89.59, direction = "right"},
        {time = 90.27, direction = "up"},
        {time = 91.04, direction = "up"},
        {time = 91.80, direction = "up"},
        {time = 92.56, direction = "up"},
        {time = 93.30, direction = "up"},
        {time = 93.96, direction = "down"},
        {time = 94.69, direction = "left"},
        {time = 95.42, direction = "down"},

        -- 96-104 seconds
        -- Complex Sequence
        {time = 96.19, direction = "left"},
        {time = 96.94, direction = "right"},
        {time = 97.67, direction = "down"},
        {time = 98.44, direction = "left"},
        {time = 99.18, direction = "down"},
        {time = 99.91, direction = "up"},
        {time = 100.65, direction = "left"},
        {time = 101.36, direction = "right"},
        {time = 102.09, direction = "down"},
        {time = 102.88, direction = "up"},
        {time = 103.63, direction = "left"},

        -- 104-112 seconds
        -- Complex Sequence
        {time = 104.38, direction = "right"},
        {time = 105.09, direction = "down"},
        {time = 105.89, direction = "up"},
        {time = 106.57, direction = "left"},
        {time = 107.29, direction = "right"},
        {time = 108.05, direction = "down"},
        {time = 108.78, direction = "up"},
        {time = 109.54, direction = "left"},
        {time = 110.27, direction = "right"},
        {time = 111.02, direction = "down"},
        {time = 111.79, direction = "up"},

        -- 112-120 seconds
        -- Complex Sequence
        {time = 112.50, direction = "left"},
        {time = 113.23, direction = "right"},
        {time = 113.97, direction = "down"},
        {time = 114.74, direction = "up"},
        {time = 115.44, direction = "left"},
        {time = 116.17, direction = "right"},
        {time = 116.99, direction = "up"},
        {time = 117.74, direction = "right"},
        {time = 118.46, direction = "right"},
        {time = 119.19, direction = "down"},
        {time = 119.93, direction = "right"},

        -- 120-128 seconds
        -- Complex Sequence
        {time = 120.72, direction = "down"},
        {time = 121.41, direction = "left"},
        {time = 122.16, direction = "down"},
        {time = 122.86, direction = "right"},
        {time = 123.65, direction = "down"},
        {time = 124.35, direction = "right"},
        {time = 125.13, direction = "down"},
        {time = 125.85, direction = "right"},
        {time = 126.63, direction = "down"},
        {time = 127.33, direction = "right"},

        -- 128-136 seconds
        -- Intense Pattern
        {time = 128.11, direction = "down"},
        {time = 128.81, direction = "right"},
        {time = 129.56, direction = "down"},
        {time = 130.33, direction = "left"},
        {time = 131.02, direction = "left"},
        {time = 131.40, direction = "left"},
        {time = 131.82, direction = "left"},
        {time = 132.25, direction = "left"},
        {time = 132.63, direction = "right"},
        {time = 132.98, direction = "right"},
        {time = 134.25, direction = "down"},
        {time = 134.64, direction = "up"},
        {time = 135.03, direction = "down"},
        {time = 135.41, direction = "up"},
        {time = 135.78, direction = "left"},

        -- 136-144 seconds
        -- Intense Pattern
        {time = 136.21, direction = "right"},
        {time = 136.54, direction = "left"},
        {time = 136.95, direction = "right"},
        {time = 137.35, direction = "left"},
        {time = 137.73, direction = "right"},
        {time = 138.09, direction = "left"},
        {time = 138.43, direction = "right"},
        {time = 139.53, direction = "right"},
        {time = 140.44, direction = "right"},
        {time = 141.06, direction = "left"},
        {time = 141.39, direction = "right"},
        {time = 141.81, direction = "left"},
        {time = 142.19, direction = "left"},
        {time = 142.54, direction = "left"},
        {time = 142.92, direction = "left"},
        {time = 143.29, direction = "left"},
        {time = 143.65, direction = "left"},
        {time = 143.99, direction = "right"},

        -- 144-152 seconds
        -- Complex Sequence
        {time = 144.37, direction = "right"},
        {time = 144.72, direction = "right"},
        {time = 145.44, direction = "up"},
        {time = 145.83, direction = "down"},
        {time = 146.44, direction = "up"},
        {time = 146.75, direction = "left"},
        {time = 147.06, direction = "right"},
        {time = 147.78, direction = "left"},
        {time = 148.23, direction = "down"}
    }
}