return {
    name = "simp",
    audio = "assets/simp.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 0.51, direction = "left"},
        {time = 1.41, direction = "right"},
        {time = 2.20, direction = "left"},
        {time = 2.91, direction = "right"},
        {time = 3.67, direction = "up"},
        {time = 4.39, direction = "down"},
        {time = 5.22, direction = "left"},
        {time = 5.53, direction = "right"},
        {time = 5.90, direction = "up"},
        {time = 6.26, direction = "down"},
        {time = 6.65, direction = "left"},
        {time = 7.41, direction = "right"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 8.17, direction = "left"},
        {time = 8.86, direction = "right"},
        {time = 9.62, direction = "up"},
        {time = 11.18, direction = "left"},
        {time = 11.57, direction = "right"},
        {time = 11.91, direction = "left"},
        {time = 12.26, direction = "right"},
        {time = 12.61, direction = "up"},
        {time = 13.00, direction = "down"},
        {time = 13.40, direction = "up"},
        {time = 13.77, direction = "down"},
        {time = 14.12, direction = "left"},
        {time = 14.45, direction = "right"},
        {time = 15.24, direction = "down"},
        {time = 15.99, direction = "left"},

        -- 16-24 seconds
        -- Complex Sequence
        {time = 16.75, direction = "left"},
        {time = 17.45, direction = "down"},
        {time = 18.29, direction = "left"},
        {time = 18.98, direction = "down"},
        {time = 19.75, direction = "left"},
        {time = 20.50, direction = "down"},
        {time = 21.23, direction = "right"},
        {time = 22.02, direction = "down"},
        {time = 22.74, direction = "right"},
        {time = 23.51, direction = "up"},

        -- 24-32 seconds
        -- Complex Sequence
        {time = 24.68, direction = "down"},
        {time = 25.41, direction = "left"},
        {time = 26.15, direction = "up"},
        {time = 26.90, direction = "down"},
        {time = 27.64, direction = "left"},
        {time = 28.37, direction = "right"},
        {time = 29.17, direction = "up"},
        {time = 29.90, direction = "down"},
        {time = 30.66, direction = "left"},
        {time = 31.38, direction = "right"},

        -- 32-40 seconds
        -- Complex Sequence
        {time = 32.14, direction = "left"},
        {time = 32.89, direction = "right"},
        {time = 33.65, direction = "down"},
        {time = 34.36, direction = "up"},
        {time = 35.15, direction = "down"},
        {time = 35.87, direction = "left"},
        {time = 36.61, direction = "right"},
        {time = 37.39, direction = "up"},
        {time = 38.11, direction = "down"},
        {time = 38.93, direction = "down"},
        {time = 39.68, direction = "left"},

        -- 40-48 seconds
        -- Complex Sequence
        {time = 40.45, direction = "right"},
        {time = 41.17, direction = "up"},
        {time = 41.83, direction = "up"},
        {time = 42.63, direction = "down"},
        {time = 43.42, direction = "left"},
        {time = 44.15, direction = "right"},
        {time = 44.89, direction = "up"},
        {time = 45.58, direction = "down"},
        {time = 46.35, direction = "left"},
        {time = 47.15, direction = "right"},
        {time = 47.85, direction = "up"},

        -- 48-56 seconds
        -- Complex Sequence
        {time = 48.53, direction = "down"},
        {time = 49.33, direction = "left"},
        {time = 50.16, direction = "right"},
        {time = 50.97, direction = "left"},
        {time = 51.74, direction = "down"},
        {time = 52.39, direction = "left"},
        {time = 53.17, direction = "down"},
        {time = 53.89, direction = "left"},
        {time = 54.58, direction = "left"},
        {time = 55.29, direction = "right"},

        -- 56-64 seconds
        -- Intense Pattern
        {time = 56.10, direction = "up"},
        {time = 56.87, direction = "down"},
        {time = 57.61, direction = "left"},
        {time = 58.36, direction = "right"},
        {time = 59.13, direction = "up"},
        {time = 59.85, direction = "down"},
        {time = 60.58, direction = "left"},
        {time = 61.30, direction = "right"},
        {time = 61.77, direction = "up"},
        {time = 62.13, direction = "down"},
        {time = 62.54, direction = "right"},
        {time = 62.93, direction = "left"},
        {time = 63.66, direction = "right"},

        -- 64-72 seconds
        -- Intense Pattern
        {time = 64.04, direction = "right"},
        {time = 64.39, direction = "right"},
        {time = 64.75, direction = "right"},
        {time = 65.14, direction = "left"},
        {time = 65.54, direction = "left"},
        {time = 65.94, direction = "left"},
        {time = 66.31, direction = "left"},
        {time = 66.68, direction = "up"},
        {time = 67.01, direction = "up"},
        {time = 67.38, direction = "down"},
        {time = 67.77, direction = "down"},
        {time = 68.20, direction = "left"},
        {time = 68.56, direction = "right"},
        {time = 68.94, direction = "left"},
        {time = 69.28, direction = "right"},
        {time = 69.69, direction = "up"},
        {time = 70.43, direction = "down"},
        {time = 71.21, direction = "left"},
        {time = 71.97, direction = "right"},

        -- 72-80 seconds
        -- Complex Sequence
        {time = 72.67, direction = "up"},
        {time = 73.71, direction = "down"},
        {time = 74.11, direction = "left"},
        {time = 74.52, direction = "right"},
        {time = 74.91, direction = "left"},
        {time = 75.30, direction = "right"},
        {time = 75.64, direction = "left"},
        {time = 76.42, direction = "up"},
        {time = 77.12, direction = "left"},
        {time = 77.91, direction = "left"},
        {time = 78.65, direction = "down"},
        {time = 79.41, direction = "up"},

        -- 80-88 seconds
        -- Intense Pattern
        {time = 80.12, direction = "down"},
        {time = 80.88, direction = "left"},
        {time = 81.63, direction = "down"},
        {time = 82.43, direction = "left"},
        {time = 82.78, direction = "right"},
        {time = 83.14, direction = "up"},
        {time = 83.50, direction = "down"},
        {time = 83.91, direction = "left"},
        {time = 84.27, direction = "right"},
        {time = 84.68, direction = "up"},
        {time = 85.03, direction = "down"},
        {time = 85.39, direction = "left"},
        {time = 85.78, direction = "right"},
        {time = 86.14, direction = "left"},
        {time = 86.51, direction = "right"},
        {time = 86.87, direction = "up"},
        {time = 87.23, direction = "down"},
        {time = 87.63, direction = "left"},

        -- 88-96 seconds
        -- Intense Pattern
        {time = 88.03, direction = "right"},
        {time = 88.40, direction = "left"},
        {time = 88.76, direction = "right"},
        {time = 89.13, direction = "left"},
        {time = 89.49, direction = "right"},
        {time = 89.87, direction = "left"},
        {time = 90.73, direction = "up"},
        {time = 91.44, direction = "down"},
        {time = 92.14, direction = "down"},
        {time = 92.90, direction = "left"},
        {time = 93.68, direction = "left"},
        {time = 94.43, direction = "down"},
        {time = 95.17, direction = "left"},
        {time = 95.34, direction = "left"},
        {time = 95.74, direction = "right"},

        -- 96-104 seconds
        -- Intense Pattern
        {time = 96.64, direction = "left"},
        {time = 97.08, direction = "left"},
        {time = 97.42, direction = "right"},
        {time = 98.15, direction = "left"},
        {time = 98.36, direction = "left"},
        {time = 98.74, direction = "right"},
        {time = 99.67, direction = "left"},
        {time = 100.39, direction = "right"},
        {time = 101.12, direction = "left"},
        {time = 101.30, direction = "left"},
        {time = 101.66, direction = "right"},
        {time = 102.66, direction = "up"},
        {time = 103.35, direction = "down"},

        -- 104-112 seconds
        -- Intense Pattern
        {time = 104.13, direction = "right"},
        {time = 105.01, direction = "left"},
        {time = 105.71, direction = "right"},
        {time = 106.06, direction = "right"},
        {time = 106.40, direction = "left"},
        {time = 106.78, direction = "right"},
        {time = 107.17, direction = "left"},
        {time = 107.56, direction = "right"},
        {time = 108.25, direction = "up"},
        {time = 108.63, direction = "down"},
        {time = 109.02, direction = "left"},
        {time = 109.42, direction = "right"},
        {time = 109.81, direction = "left"},
        {time = 110.18, direction = "right"},
        {time = 110.53, direction = "left"},
        {time = 110.88, direction = "right"},
        {time = 111.27, direction = "left"},
        {time = 111.63, direction = "right"},

        -- 112-120 seconds
        -- Intense Pattern
        {time = 112.05, direction = "right"},
        {time = 112.38, direction = "up"},
        {time = 112.83, direction = "down"},
        {time = 113.61, direction = "left"},
        {time = 113.94, direction = "right"},
        {time = 114.29, direction = "left"},
        {time = 114.65, direction = "right"},
        {time = 114.99, direction = "up"},
        {time = 115.38, direction = "down"},
        {time = 115.78, direction = "left"},
        {time = 116.17, direction = "right"},
        {time = 116.54, direction = "left"},
        {time = 116.92, direction = "right"},
        {time = 117.55, direction = "up"},
        {time = 117.83, direction = "down"}
    }
}