return {
    name = "Kawaii Language Learning Adventure ✨",
    audio = "assets/Kawaii Language Learning Adventure ✨.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 0.79, direction = "left"},
        {time = 1.54, direction = "right"},
        {time = 2.28, direction = "down"},
        {time = 2.91, direction = "left"},
        {time = 3.64, direction = "right"},
        {time = 4.28, direction = "up"},
        {time = 4.96, direction = "down"},
        {time = 5.63, direction = "left"},
        {time = 6.09, direction = "right"},
        {time = 6.45, direction = "left"},
        {time = 6.79, direction = "up"},
        {time = 7.28, direction = "right"},
        {time = 7.58, direction = "down"},
        {time = 7.87, direction = "right"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 8.35, direction = "down"},
        {time = 8.81, direction = "right"},
        {time = 9.16, direction = "left"},
        {time = 9.78, direction = "up"},
        {time = 10.54, direction = "left"},
        {time = 11.30, direction = "right"},
        {time = 11.58, direction = "down"},
        {time = 11.89, direction = "right"},
        {time = 12.23, direction = "left"},
        {time = 12.58, direction = "up"},
        {time = 13.25, direction = "down"},
        {time = 13.96, direction = "up"},
        {time = 14.62, direction = "left"},
        {time = 15.30, direction = "down"},

        -- 16-24 seconds
        -- Intense Pattern
        {time = 16.01, direction = "left"},
        {time = 16.71, direction = "up"},
        {time = 17.35, direction = "right"},
        {time = 18.11, direction = "left"},
        {time = 18.74, direction = "right"},
        {time = 19.38, direction = "left"},
        {time = 19.71, direction = "right"},
        {time = 20.06, direction = "up"},
        {time = 20.40, direction = "down"},
        {time = 20.79, direction = "left"},
        {time = 21.09, direction = "right"},
        {time = 21.46, direction = "left"},
        {time = 21.78, direction = "left"},
        {time = 22.12, direction = "right"},
        {time = 22.43, direction = "right"},
        {time = 22.82, direction = "up"},
        {time = 23.14, direction = "up"},
        {time = 23.43, direction = "down"},
        {time = 23.77, direction = "down"},

        -- 24-32 seconds
        -- Intense Pattern
        {time = 24.11, direction = "left"},
        {time = 24.44, direction = "left"},
        {time = 24.82, direction = "right"},
        {time = 25.12, direction = "right"},
        {time = 25.52, direction = "up"},
        {time = 25.80, direction = "up"},
        {time = 26.16, direction = "down"},
        {time = 26.47, direction = "down"},
        {time = 26.81, direction = "left"},
        {time = 27.14, direction = "left"},
        {time = 27.50, direction = "right"},
        {time = 27.82, direction = "right"},
        {time = 28.22, direction = "up"},
        {time = 28.52, direction = "up"},
        {time = 28.95, direction = "down"},
        {time = 29.26, direction = "down"},
        {time = 29.61, direction = "left"},
        {time = 29.93, direction = "left"},
        {time = 30.25, direction = "right"},
        {time = 30.52, direction = "right"},
        {time = 30.94, direction = "up"},
        {time = 31.25, direction = "up"},
        {time = 31.61, direction = "left"},

        -- 32-40 seconds
        -- Intense Pattern
        {time = 32.26, direction = "right"},
        {time = 33.10, direction = "left"},
        {time = 33.73, direction = "right"},
        {time = 34.36, direction = "right"},
        {time = 35.07, direction = "down"},
        {time = 35.78, direction = "right"},
        {time = 36.48, direction = "down"},
        {time = 37.11, direction = "up"},
        {time = 37.75, direction = "right"},
        {time = 38.43, direction = "left"},
        {time = 39.15, direction = "right"},
        {time = 39.44, direction = "down"},
        {time = 39.83, direction = "left"},

        -- 40-48 seconds
        -- Intense Pattern
        {time = 40.21, direction = "up"},
        {time = 40.57, direction = "left"},
        {time = 40.88, direction = "up"},
        {time = 41.19, direction = "right"},
        {time = 41.58, direction = "down"},
        {time = 41.90, direction = "left"},
        {time = 42.22, direction = "up"},
        {time = 42.53, direction = "right"},
        {time = 42.93, direction = "down"},
        {time = 43.26, direction = "left"},
        {time = 43.57, direction = "up"},
        {time = 43.92, direction = "right"},
        {time = 44.33, direction = "left"},
        {time = 44.64, direction = "up"},
        {time = 44.97, direction = "down"},
        {time = 45.26, direction = "right"},
        {time = 45.68, direction = "up"},
        {time = 45.99, direction = "down"},
        {time = 46.35, direction = "left"},
        {time = 46.63, direction = "up"},
        {time = 46.95, direction = "right"},
        {time = 47.29, direction = "down"},
        {time = 47.68, direction = "up"},

        -- 48-56 seconds
        -- Intense Pattern
        {time = 48.01, direction = "left"},
        {time = 48.36, direction = "up"},
        {time = 48.68, direction = "down"},
        {time = 49.01, direction = "right"},
        {time = 49.34, direction = "up"},
        {time = 49.67, direction = "down"},
        {time = 50.05, direction = "left"},
        {time = 50.36, direction = "right"},
        {time = 50.74, direction = "left"},
        {time = 51.06, direction = "right"},
        {time = 51.44, direction = "up"},
        {time = 51.77, direction = "down"},
        {time = 52.07, direction = "left"},
        {time = 52.41, direction = "right"},
        {time = 52.86, direction = "up"},
        {time = 53.51, direction = "up"},
        {time = 54.15, direction = "right"},
        {time = 54.79, direction = "up"},
        {time = 55.53, direction = "left"},
        {time = 55.83, direction = "right"},

        -- 56-64 seconds
        -- Intense Pattern
        {time = 56.22, direction = "up"},
        {time = 56.91, direction = "down"},
        {time = 57.57, direction = "left"},
        {time = 57.88, direction = "right"},
        {time = 58.24, direction = "left"},
        {time = 58.98, direction = "down"},
        {time = 59.69, direction = "left"},
        {time = 60.41, direction = "up"},
        {time = 60.66, direction = "right"},
        {time = 61.01, direction = "down"},
        {time = 61.67, direction = "left"},
        {time = 62.33, direction = "left"},
        {time = 62.69, direction = "right"},
        {time = 63.04, direction = "down"},
        {time = 63.34, direction = "left"},
        {time = 63.72, direction = "up"},

        -- 64-72 seconds
        -- Intense Pattern
        {time = 64.33, direction = "up"},
        {time = 64.69, direction = "down"},
        {time = 65.07, direction = "left"},
        {time = 65.48, direction = "right"},
        {time = 65.78, direction = "left"},
        {time = 66.04, direction = "right"},
        {time = 67.09, direction = "down"},
        {time = 67.45, direction = "down"},
        {time = 67.77, direction = "left"},
        {time = 68.10, direction = "up"},
        {time = 68.47, direction = "up"},
        {time = 68.75, direction = "up"},
        {time = 69.08, direction = "left"},
        {time = 69.41, direction = "right"},
        {time = 69.77, direction = "left"},
        {time = 70.13, direction = "right"},
        {time = 70.48, direction = "up"},
        {time = 70.82, direction = "down"},
        {time = 71.18, direction = "left"},
        {time = 71.49, direction = "right"},
        {time = 71.86, direction = "left"},

        -- 72-80 seconds
        -- Intense Pattern
        {time = 72.59, direction = "down"},
        {time = 73.27, direction = "right"},
        {time = 73.98, direction = "down"},
        {time = 74.65, direction = "right"},
        {time = 75.31, direction = "up"},
        {time = 75.99, direction = "right"},
        {time = 76.67, direction = "left"},
        {time = 77.35, direction = "right"},
        {time = 77.71, direction = "left"},
        {time = 78.05, direction = "right"},
        {time = 78.36, direction = "left"},
        {time = 78.68, direction = "up"},
        {time = 78.99, direction = "down"},
        {time = 79.38, direction = "left"},
        {time = 79.70, direction = "right"},

        -- 80-88 seconds
        -- Intense Pattern
        {time = 80.06, direction = "left"},
        {time = 80.44, direction = "left"},
        {time = 80.80, direction = "right"},
        {time = 81.14, direction = "right"},
        {time = 81.47, direction = "left"},
        {time = 81.85, direction = "left"},
        {time = 82.16, direction = "right"},
        {time = 82.46, direction = "right"},
        {time = 82.80, direction = "left"},
        {time = 83.15, direction = "left"},
        {time = 83.49, direction = "up"},
        {time = 83.80, direction = "up"},
        {time = 84.16, direction = "down"},
        {time = 84.51, direction = "down"},
        {time = 84.88, direction = "left"},
        {time = 85.25, direction = "left"},
        {time = 85.57, direction = "right"},
        {time = 85.91, direction = "right"},
        {time = 86.23, direction = "up"},
        {time = 86.55, direction = "up"},
        {time = 86.88, direction = "down"},
        {time = 87.23, direction = "down"},
        {time = 87.58, direction = "left"},
        {time = 87.94, direction = "left"},

        -- 88-96 seconds
        -- Intense Pattern
        {time = 88.28, direction = "right"},
        {time = 88.59, direction = "right"},
        {time = 88.97, direction = "up"},
        {time = 89.26, direction = "up"},
        {time = 89.60, direction = "down"},
        {time = 89.89, direction = "down"},
        {time = 90.21, direction = "left"},
        {time = 90.54, direction = "left"},
        {time = 90.88, direction = "right"},
        {time = 91.21, direction = "right"},
        {time = 91.61, direction = "up"},
        {time = 91.93, direction = "up"},
        {time = 92.29, direction = "down"},
        {time = 92.55, direction = "down"},
        {time = 92.99, direction = "left"},
        {time = 93.29, direction = "left"},
        {time = 93.65, direction = "right"},
        {time = 93.95, direction = "right"},
        {time = 94.35, direction = "up"},
        {time = 94.65, direction = "up"},
        {time = 95.26, direction = "down"},
        {time = 95.68, direction = "down"},

        -- 96-104 seconds
        -- Intense Pattern
        {time = 96.43, direction = "up"},
        {time = 96.56, direction = "up"},
        {time = 97.16, direction = "down"},
        {time = 97.73, direction = "right"},
        {time = 98.42, direction = "left"},
        {time = 99.12, direction = "right"},
        {time = 99.48, direction = "left"},
        {time = 99.81, direction = "right"},
        {time = 100.15, direction = "up"},
        {time = 100.53, direction = "down"},
        {time = 100.85, direction = "left"},
        {time = 101.21, direction = "right"},
        {time = 101.55, direction = "left"},
        {time = 101.92, direction = "right"},
        {time = 102.28, direction = "right"},
        {time = 102.65, direction = "left"},
        {time = 102.98, direction = "left"},
        {time = 103.30, direction = "right"},
        {time = 103.58, direction = "right"},
        {time = 103.92, direction = "down"},

        -- 104-112 seconds
        -- Intense Pattern
        {time = 104.65, direction = "up"},
        {time = 104.97, direction = "up"},
        {time = 105.33, direction = "down"},
        {time = 105.63, direction = "down"},
        {time = 105.94, direction = "left"},
        {time = 106.27, direction = "left"},
        {time = 106.62, direction = "right"},
        {time = 106.98, direction = "right"},
        {time = 107.35, direction = "left"},
        {time = 107.84, direction = "up"},
        {time = 108.18, direction = "down"},
        {time = 108.57, direction = "right"},
        {time = 109.35, direction = "right"},
        {time = 110.14, direction = "down"},
        {time = 110.83, direction = "right"},
        {time = 111.58, direction = "left"},

        -- 112-120 seconds
        -- Intense Pattern
        {time = 112.16, direction = "left"},
        {time = 112.46, direction = "right"},
        {time = 112.80, direction = "down"},
        {time = 113.13, direction = "up"},
        {time = 113.49, direction = "left"},
        {time = 113.82, direction = "right"},
        {time = 114.18, direction = "down"},
        {time = 114.81, direction = "left"},
        {time = 115.11, direction = "right"},
        {time = 115.48, direction = "down"},
        {time = 115.81, direction = "left"},
        {time = 116.13, direction = "right"},
        {time = 116.46, direction = "left"},
        {time = 116.82, direction = "right"},
        {time = 117.20, direction = "up"},
        {time = 117.52, direction = "down"},
        {time = 117.87, direction = "left"},
        {time = 118.23, direction = "right"},
        {time = 118.56, direction = "left"},
        {time = 118.92, direction = "up"},
        {time = 119.27, direction = "down"},
        {time = 119.64, direction = "left"},
        {time = 119.97, direction = "right"},

        -- 120-128 seconds
        -- Intense Pattern
        {time = 120.35, direction = "left"},
        {time = 120.68, direction = "up"},
        {time = 121.03, direction = "down"},
        {time = 121.33, direction = "left"},
        {time = 121.67, direction = "right"},
        {time = 122.40, direction = "right"},
        {time = 123.02, direction = "down"},
        {time = 123.78, direction = "up"},
        {time = 124.39, direction = "down"},
        {time = 125.07, direction = "right"},
        {time = 125.43, direction = "left"},
        {time = 125.75, direction = "up"},
        {time = 126.07, direction = "down"},
        {time = 126.36, direction = "right"},
        {time = 126.88, direction = "up"},
        {time = 127.28, direction = "left"},
        {time = 127.57, direction = "right"},
        {time = 127.89, direction = "left"},

        -- 128-136 seconds
        -- Intense Pattern
        {time = 128.19, direction = "right"},
        {time = 128.50, direction = "left"},
        {time = 128.80, direction = "right"},
        {time = 129.15, direction = "left"},
        {time = 129.52, direction = "left"},
        {time = 129.84, direction = "right"},
        {time = 130.16, direction = "right"},
        {time = 130.48, direction = "down"},
        {time = 130.83, direction = "up"},
        {time = 131.17, direction = "down"},
        {time = 131.87, direction = "right"},
        {time = 132.21, direction = "left"},
        {time = 132.57, direction = "up"},
        {time = 132.92, direction = "down"},
        {time = 133.23, direction = "up"},
        {time = 133.58, direction = "down"},
        {time = 133.96, direction = "left"},
        {time = 134.28, direction = "right"},
        {time = 134.64, direction = "up"},
        {time = 134.97, direction = "down"},
        {time = 135.30, direction = "left"},
        {time = 135.62, direction = "right"},

        -- 136-144 seconds
        -- Intense Pattern
        {time = 136.01, direction = "up"},
        {time = 136.32, direction = "down"},
        {time = 136.66, direction = "left"},
        {time = 136.99, direction = "right"},
        {time = 137.49, direction = "up"},
        {time = 137.75, direction = "right"},
        {time = 138.10, direction = "right"},
        {time = 138.38, direction = "up"},
        {time = 138.71, direction = "down"},
        {time = 139.02, direction = "left"},
        {time = 139.36, direction = "up"},
        {time = 139.71, direction = "down"},
        {time = 140.06, direction = "left"},
        {time = 140.46, direction = "left"},
        {time = 141.20, direction = "right"},
        {time = 142.01, direction = "left"},
        {time = 142.79, direction = "right"},
        {time = 143.47, direction = "right"},

        -- 144-152 seconds
        -- Intense Pattern
        {time = 144.14, direction = "down"},
        {time = 144.84, direction = "right"},
        {time = 145.54, direction = "up"},
        {time = 146.27, direction = "left"},
        {time = 146.63, direction = "left"},
        {time = 146.90, direction = "right"},
        {time = 147.26, direction = "right"},
        {time = 147.60, direction = "right"},
        {time = 147.94, direction = "right"},
        {time = 148.29, direction = "left"},
        {time = 148.58, direction = "right"},
        {time = 148.97, direction = "left"},
        {time = 149.30, direction = "right"},
        {time = 149.67, direction = "up"},
        {time = 150.02, direction = "down"},
        {time = 150.39, direction = "left"},
        {time = 150.70, direction = "right"},
        {time = 151.02, direction = "up"},
        {time = 151.33, direction = "down"},
        {time = 151.67, direction = "left"},

        -- 152-160 seconds
        -- Intense Pattern
        {time = 152.01, direction = "right"},
        {time = 152.34, direction = "up"},
        {time = 152.68, direction = "down"},
        {time = 153.05, direction = "left"},
        {time = 153.39, direction = "right"},
        {time = 153.68, direction = "up"},
        {time = 154.00, direction = "down"},
        {time = 154.37, direction = "left"},
        {time = 154.72, direction = "right"},
        {time = 155.10, direction = "left"},
        {time = 155.47, direction = "left"},
        {time = 155.81, direction = "left"},
        {time = 156.12, direction = "left"},
        {time = 156.46, direction = "right"},
        {time = 156.80, direction = "right"},
        {time = 157.11, direction = "right"},
        {time = 157.44, direction = "right"},
        {time = 157.75, direction = "up"},
        {time = 158.10, direction = "up"},
        {time = 158.43, direction = "up"},
        {time = 158.82, direction = "up"},
        {time = 159.15, direction = "down"},
        {time = 159.51, direction = "down"},
        {time = 159.80, direction = "down"},

        -- 160-168 seconds
        -- Intense Pattern
        {time = 160.18, direction = "up"},
        {time = 160.47, direction = "up"},
        {time = 160.78, direction = "left"},
        {time = 161.15, direction = "right"},
        {time = 161.49, direction = "up"},
        {time = 161.88, direction = "down"},
        {time = 162.23, direction = "up"},
        {time = 162.57, direction = "down"},
        {time = 162.94, direction = "up"},
        {time = 163.24, direction = "down"},
        {time = 163.60, direction = "left"},
        {time = 163.95, direction = "right"},
        {time = 164.76, direction = "up"},
        {time = 165.35, direction = "down"},
        {time = 165.94, direction = "left"},
        {time = 166.68, direction = "right"},
        {time = 167.36, direction = "left"},
        {time = 167.70, direction = "up"},

        -- 168-176 seconds
        -- Intense Pattern
        {time = 168.04, direction = "down"},
        {time = 168.38, direction = "left"},
        {time = 168.73, direction = "right"},
        {time = 169.07, direction = "up"},
        {time = 169.39, direction = "down"},
        {time = 169.75, direction = "up"},
        {time = 170.09, direction = "left"},
        {time = 170.80, direction = "right"},
        {time = 171.48, direction = "up"},
        {time = 171.80, direction = "down"},
        {time = 172.17, direction = "up"},
        {time = 172.84, direction = "left"},
        {time = 173.53, direction = "right"},
        {time = 174.15, direction = "left"},
        {time = 174.48, direction = "up"},
        {time = 174.82, direction = "down"},
        {time = 175.15, direction = "up"},
        {time = 175.50, direction = "left"},

        -- 176-184 seconds
        -- Intense Pattern
        {time = 176.22, direction = "right"},
        {time = 176.95, direction = "down"},
        {time = 177.67, direction = "left"},
        {time = 178.30, direction = "left"},
        {time = 178.65, direction = "right"},
        {time = 178.98, direction = "left"},
        {time = 179.29, direction = "right"},
        {time = 179.99, direction = "left"},
        {time = 180.34, direction = "right"},
        {time = 180.66, direction = "left"},
        {time = 181.33, direction = "right"},
        {time = 182.03, direction = "left"},
        {time = 182.74, direction = "right"},
        {time = 183.40, direction = "down"},
        {time = 183.72, direction = "up"},

        -- 184-192 seconds
        -- Intense Pattern
        {time = 184.04, direction = "left"},
        {time = 184.40, direction = "right"},
        {time = 184.76, direction = "down"},
        {time = 185.12, direction = "up"},
        {time = 185.44, direction = "down"},
        {time = 185.78, direction = "left"},
        {time = 186.12, direction = "right"},
        {time = 186.44, direction = "up"},
        {time = 186.76, direction = "down"},
        {time = 187.11, direction = "up"},
        {time = 187.44, direction = "down"},
        {time = 187.79, direction = "left"},
        {time = 188.16, direction = "right"},
        {time = 188.54, direction = "up"},
        {time = 189.22, direction = "down"},
        {time = 189.83, direction = "up"},
        {time = 190.55, direction = "down"},
        {time = 191.28, direction = "up"},
        {time = 191.93, direction = "left"},

        -- 192-200 seconds
        -- Complex Sequence
        {time = 192.59, direction = "right"},
        {time = 193.25, direction = "down"},
        {time = 194.00, direction = "up"},
        {time = 194.72, direction = "down"},
        {time = 195.39, direction = "left"},
        {time = 196.01, direction = "right"},
        {time = 196.71, direction = "down"},
        {time = 197.39, direction = "up"},
        {time = 197.71, direction = "down"},
        {time = 198.05, direction = "left"},
        {time = 198.81, direction = "right"},
        {time = 199.43, direction = "down"},

        -- 200-208 seconds
        -- Simple Sequence
        {time = 200.14, direction = "up"},
        {time = 200.81, direction = "left"},
        {time = 201.46, direction = "right"}
    }
}