return {
    name = "Laser Eyes More Like Drying Eyes",
    audio = "assets/Laser Eyes More Like Drying Eyes.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 0.41, direction = "left"},
        {time = 1.03, direction = "right"},
        {time = 1.70, direction = "left"},
        {time = 2.37, direction = "down"},
        {time = 3.05, direction = "left"},
        {time = 3.78, direction = "right"},
        {time = 4.41, direction = "up"},
        {time = 5.05, direction = "down"},
        {time = 5.72, direction = "left"},
        {time = 6.36, direction = "right"},
        {time = 7.03, direction = "right"},
        {time = 7.66, direction = "up"},

        -- 8-16 seconds
        -- Complex Sequence
        {time = 8.30, direction = "down"},
        {time = 9.13, direction = "left"},
        {time = 9.61, direction = "right"},
        {time = 10.32, direction = "up"},
        {time = 11.06, direction = "left"},
        {time = 11.72, direction = "down"},
        {time = 12.40, direction = "left"},
        {time = 12.92, direction = "down"},
        {time = 13.65, direction = "up"},
        {time = 14.31, direction = "down"},
        {time = 14.99, direction = "left"},
        {time = 15.62, direction = "down"},

        -- 16-24 seconds
        -- Intense Pattern
        {time = 16.33, direction = "left"},
        {time = 16.70, direction = "left"},
        {time = 17.03, direction = "left"},
        {time = 17.35, direction = "right"},
        {time = 17.70, direction = "right"},
        {time = 18.02, direction = "right"},
        {time = 18.28, direction = "right"},
        {time = 18.67, direction = "up"},
        {time = 19.05, direction = "down"},
        {time = 19.40, direction = "left"},
        {time = 20.04, direction = "left"},
        {time = 20.72, direction = "right"},
        {time = 21.38, direction = "left"},
        {time = 22.07, direction = "up"},
        {time = 22.77, direction = "down"},
        {time = 23.42, direction = "left"},

        -- 24-32 seconds
        -- Complex Sequence
        {time = 24.10, direction = "right"},
        {time = 24.80, direction = "left"},
        {time = 25.44, direction = "right"},
        {time = 26.08, direction = "left"},
        {time = 27.36, direction = "left"},
        {time = 28.03, direction = "right"},
        {time = 28.72, direction = "left"},
        {time = 29.39, direction = "up"},
        {time = 30.04, direction = "right"},
        {time = 30.71, direction = "down"},
        {time = 31.38, direction = "left"},

        -- 32-40 seconds
        -- Complex Sequence
        {time = 32.06, direction = "left"},
        {time = 32.76, direction = "up"},
        {time = 33.37, direction = "right"},
        {time = 34.13, direction = "left"},
        {time = 34.67, direction = "up"},
        {time = 35.26, direction = "down"},
        {time = 36.01, direction = "right"},
        {time = 36.76, direction = "left"},
        {time = 37.35, direction = "right"},
        {time = 38.06, direction = "left"},
        {time = 38.59, direction = "up"},
        {time = 39.39, direction = "down"},

        -- 40-48 seconds
        -- Complex Sequence
        {time = 40.11, direction = "right"},
        {time = 40.90, direction = "left"},
        {time = 41.68, direction = "up"},
        {time = 42.39, direction = "right"},
        {time = 43.08, direction = "left"},
        {time = 43.71, direction = "right"},
        {time = 44.41, direction = "left"},
        {time = 44.99, direction = "up"},
        {time = 45.62, direction = "down"},
        {time = 46.35, direction = "right"},
        {time = 46.95, direction = "left"},
        {time = 47.57, direction = "left"},

        -- 48-56 seconds
        -- Complex Sequence
        {time = 48.17, direction = "down"},
        {time = 48.96, direction = "left"},
        {time = 49.68, direction = "down"},
        {time = 50.33, direction = "down"},
        {time = 50.98, direction = "left"},
        {time = 51.74, direction = "left"},
        {time = 52.33, direction = "up"},
        {time = 52.94, direction = "right"},
        {time = 53.66, direction = "left"},
        {time = 54.43, direction = "up"},
        {time = 54.98, direction = "right"},
        {time = 55.71, direction = "left"},

        -- 56-64 seconds
        -- Complex Sequence
        {time = 56.38, direction = "up"},
        {time = 57.04, direction = "right"},
        {time = 57.71, direction = "down"},
        {time = 58.32, direction = "up"},
        {time = 59.04, direction = "left"},
        {time = 59.67, direction = "right"},
        {time = 60.27, direction = "up"},
        {time = 61.04, direction = "down"},
        {time = 61.75, direction = "left"},
        {time = 62.41, direction = "right"},
        {time = 62.98, direction = "left"},
        {time = 63.69, direction = "up"},

        -- 64-72 seconds
        -- Complex Sequence
        {time = 64.39, direction = "right"},
        {time = 65.00, direction = "down"},
        {time = 65.75, direction = "left"},
        {time = 66.35, direction = "down"},
        {time = 67.04, direction = "left"},
        {time = 67.64, direction = "right"},
        {time = 68.33, direction = "up"},
        {time = 68.86, direction = "down"},
        {time = 69.62, direction = "left"},
        {time = 70.43, direction = "right"},
        {time = 71.03, direction = "right"},
        {time = 71.71, direction = "right"},

        -- 72-80 seconds
        -- Complex Sequence
        {time = 72.43, direction = "right"},
        {time = 73.05, direction = "right"},
        {time = 73.67, direction = "right"},
        {time = 74.36, direction = "right"},
        {time = 75.04, direction = "left"},
        {time = 75.79, direction = "down"},
        {time = 76.41, direction = "left"},
        {time = 77.03, direction = "left"},
        {time = 77.70, direction = "up"},
        {time = 78.32, direction = "down"},
        {time = 78.96, direction = "right"},
        {time = 79.65, direction = "left"},

        -- 80-88 seconds
        -- Complex Sequence
        {time = 80.36, direction = "right"},
        {time = 80.99, direction = "left"},
        {time = 81.69, direction = "right"},
        {time = 82.40, direction = "down"},
        {time = 83.06, direction = "left"},
        {time = 83.71, direction = "up"},
        {time = 84.40, direction = "down"},
        {time = 85.06, direction = "left"},
        {time = 85.71, direction = "left"},
        {time = 86.33, direction = "down"},
        {time = 86.95, direction = "left"},
        {time = 87.66, direction = "down"},

        -- 88-96 seconds
        -- Complex Sequence
        {time = 88.30, direction = "left"},
        {time = 88.99, direction = "down"},
        {time = 89.57, direction = "left"},
        {time = 90.23, direction = "up"},
        {time = 91.02, direction = "down"},
        {time = 91.70, direction = "right"},
        {time = 92.32, direction = "left"},
        {time = 93.03, direction = "up"},
        {time = 93.89, direction = "right"},
        {time = 94.57, direction = "right"},
        {time = 95.17, direction = "left"},
        {time = 95.62, direction = "down"},

        -- 96-104 seconds
        -- Complex Sequence
        {time = 96.30, direction = "up"},
        {time = 96.97, direction = "left"},
        {time = 97.62, direction = "right"},
        {time = 98.36, direction = "left"},
        {time = 98.97, direction = "left"},
        {time = 99.63, direction = "down"},
        {time = 100.22, direction = "up"},
        {time = 100.88, direction = "down"},
        {time = 101.68, direction = "left"},
        {time = 102.35, direction = "up"},
        {time = 102.94, direction = "down"},
        {time = 103.69, direction = "right"},

        -- 104-112 seconds
        -- Complex Sequence
        {time = 104.34, direction = "left"},
        {time = 105.03, direction = "up"},
        {time = 105.62, direction = "right"},
        {time = 106.19, direction = "left"},
        {time = 106.97, direction = "down"},
        {time = 107.63, direction = "right"},
        {time = 108.34, direction = "left"},
        {time = 109.02, direction = "up"},
        {time = 109.66, direction = "left"},
        {time = 110.30, direction = "right"},
        {time = 111.08, direction = "right"},
        {time = 111.66, direction = "left"},

        -- 112-120 seconds
        -- Complex Sequence
        {time = 112.39, direction = "left"},
        {time = 112.99, direction = "right"},
        {time = 113.58, direction = "up"},
        {time = 114.31, direction = "down"},
        {time = 114.97, direction = "left"},
        {time = 115.63, direction = "right"},
        {time = 116.33, direction = "right"},
        {time = 117.02, direction = "right"},
        {time = 117.62, direction = "left"},
        {time = 118.27, direction = "right"},
        {time = 118.95, direction = "up"},
        {time = 119.61, direction = "down"},

        -- 120-128 seconds
        -- Intense Pattern
        {time = 120.34, direction = "left"},
        {time = 120.99, direction = "right"},
        {time = 121.60, direction = "up"},
        {time = 122.31, direction = "down"},
        {time = 123.06, direction = "right"},
        {time = 123.66, direction = "left"},
        {time = 124.42, direction = "up"},
        {time = 125.01, direction = "down"},
        {time = 125.77, direction = "right"},
        {time = 126.35, direction = "left"},
        {time = 126.98, direction = "right"},
        {time = 127.39, direction = "up"},
        {time = 127.94, direction = "down"},

        -- 128-136 seconds
        -- Intense Pattern
        {time = 128.65, direction = "left"},
        {time = 129.13, direction = "right"},
        {time = 129.65, direction = "right"},
        {time = 130.28, direction = "right"},
        {time = 130.65, direction = "left"},
        {time = 131.08, direction = "right"},
        {time = 131.47, direction = "right"},
        {time = 131.76, direction = "right"},
        {time = 132.05, direction = "right"},
        {time = 132.37, direction = "left"},
        {time = 132.67, direction = "right"},
        {time = 132.99, direction = "up"},
        {time = 134.03, direction = "left"},
        {time = 134.36, direction = "right"},
        {time = 134.69, direction = "right"},
        {time = 135.02, direction = "right"},
        {time = 135.29, direction = "left"},
        {time = 135.61, direction = "up"},
        {time = 135.92, direction = "down"},

        -- 136-144 seconds
        -- Intense Pattern
        {time = 136.29, direction = "right"},
        {time = 136.65, direction = "left"},
        {time = 137.01, direction = "right"},
        {time = 137.35, direction = "left"},
        {time = 137.70, direction = "right"},
        {time = 138.04, direction = "up"},
        {time = 138.33, direction = "down"},
        {time = 138.68, direction = "left"},
        {time = 139.05, direction = "right"},
        {time = 139.43, direction = "right"},
        {time = 139.71, direction = "right"},
        {time = 140.02, direction = "left"},
        {time = 140.33, direction = "up"},
        {time = 140.66, direction = "down"},
        {time = 141.01, direction = "left"},
        {time = 141.70, direction = "up"},
        {time = 142.32, direction = "down"},
        {time = 142.99, direction = "left"},
        {time = 143.67, direction = "down"},

        -- 144-152 seconds
        -- Complex Sequence
        {time = 144.36, direction = "left"},
        {time = 145.00, direction = "right"},
        {time = 145.68, direction = "left"},
        {time = 146.37, direction = "right"},
        {time = 147.06, direction = "up"},
        {time = 147.67, direction = "down"},
        {time = 148.35, direction = "left"},
        {time = 149.00, direction = "right"},
        {time = 149.73, direction = "left"}
    }
}